from __future__ import annotations

from fastapi import HTTPException

PROJECT_NOT_FOUND = "project_not_found"
CHARACTER_NOT_FOUND = "character_not_found"
CHARACTER_NAME_CONFLICT = "character_name_conflict"
RELATION_NOT_FOUND = "relation_not_found"
RELATION_SELF_REFERENCE = "relation_self_reference"
RELATION_MISSING_CHARACTER = "relation_missing_character"
RELATION_CONFLICT = "relation_conflict"
TOME_NOT_FOUND = "tome_not_found"
CHAPTER_NOT_FOUND = "chapter_not_found"
CHAPTER_MISSING_TOME = "chapter_missing_tome"
SCENE_NOT_FOUND = "scene_not_found"
ASSET_NOT_FOUND = "asset_not_found"
ASSET_LINK_NOT_FOUND = "asset_link_not_found"
ASSET_LINK_TARGET_NOT_FOUND = "asset_link_target_not_found"
ASSET_SOURCE_MISSING = "asset_source_missing"
ASSET_ID_MUST_MATCH_ROUTE_ASSET = "asset_id_must_match_route_asset"
VERSION_NOT_FOUND = "version_not_found"
WARNING_NOT_FOUND = "warning_not_found"
EXPORT_NOT_FOUND = "export_not_found"
EXPORT_FORMAT_INVALID = "export_format_invalid"
EXPORT_ARTIFACT_NOT_AVAILABLE = "export_artifact_not_available"
EXPORT_ARTIFACT_NOT_FOUND = "export_artifact_not_found"
GENERATION_JOB_NOT_FOUND = "generation_job_not_found"
GENERATION_BOARD_NOT_FOUND = "generation_board_not_found"
GENERATION_PANEL_NOT_FOUND = "generation_panel_not_found"
GENERATION_BOARD_ARTIFACT_NOT_AVAILABLE = "generation_board_artifact_not_available"
GENERATION_BOARD_ARTIFACT_NOT_FOUND = "generation_board_artifact_not_found"
GENERATION_SOURCE_NOT_FOUND = "generation_source_not_found"
GENERATION_VERSION_NOT_FOUND = "generation_version_not_found"
GENERATION_SOURCE_KIND_INVALID = "generation_source_kind_invalid"
GENERATION_PROVIDER_FAILED = "generation_provider_failed"
GENERATION_PROVIDER_INVALID_RESPONSE = "generation_provider_invalid_response"
GENERATION_PROVIDER_NOT_IMPLEMENTED = "generation_provider_not_implemented"
MODEL_NOT_FOUND = "model_not_found"
MODEL_NOT_CONFIGURED = "model_not_configured"
MODEL_DISABLED = "model_disabled"
MODEL_MISSING_CONFIGURATION = "model_missing_configuration"
MODEL_KIND_MISMATCH = "model_kind_mismatch"
MODEL_NOT_IMPLEMENTED = "model_not_implemented"
SOURCE_CHARACTER_ID_MUST_MATCH_ROUTE_CHARACTER = "source_character_id_must_match_route_character"
SCENE_HIERARCHY_MISMATCH = "scene_hierarchy_mismatch"


def raise_api_error(status_code: int, code: str) -> None:
    raise HTTPException(status_code=status_code, detail=code)
