/**
 * Image URL utilities for character images and generation panels
 * These are not generated by the SDK and must be kept as utilities
 */
import { API_BASE_URL, backendUrl } from "~/lib/errors";

/**
 * Extended character image interface with optional publicUrl
 * Compatible with both ListCharacterImagesResponse and GetProjectCharacterImagesResponse
 */
export interface CharacterImageWithUrl {
  id: string;
  projectId: string;
  characterId: string;
  fileName: string;
  publicUrl?: string;
  filePath?: string;
  fileSize?: unknown;
  mimeType?: string | unknown;
  strategy?: string | null | unknown;
  style?: string | null | unknown;
  variationIndex?: number | null | unknown;
  createdAt?: string;
  prompt?: string;
}

/**
 * Build the URL for a character image using publicUrl from API
 * Falls back to constructing from fileName if publicUrl not available
 */
export function characterImageUrlFromData(
  image: CharacterImageWithUrl
): string {
  // If publicUrl is available and non-empty
  if (image.publicUrl && image.publicUrl.trim() !== '') {
    return backendUrl(image.publicUrl);
  }

  // Fallback: construct URL from fileName (new convention)
  // Format: /projects/{projectId}/generation/character_images/{fileName}
  return `${API_BASE_URL}/projects/${image.projectId}/generation/character_images/${image.fileName}`;
}

/**
 * @deprecated Use characterImageUrlFromData() instead with publicUrl
 * Build the URL for a character image file via API endpoint
 */
export function characterImageUrl(
  projectId: string,
  characterId: string,
  imageId: string
): string {
  return `${API_BASE_URL}/api/v1/projects/${projectId}/characters/${characterId}/images/${imageId}/file`;
}

/**
 * Build the URL for a generation panel image
 */
export function generationPanelImageUrl(
  projectId: string,
  boardId: string,
  panelId: string
): string {
  return `${API_BASE_URL}/api/projects/${projectId}/generation/boards/${boardId}/panels/${panelId}/image`;
}
