/**
 * Image URL utilities for character images and generation panels
 * These are not generated by the SDK and must be kept as utilities
 */
import { API_BASE_URL } from "~/lib/errors";

/**
 * Build the URL for a character image file
 */
export function characterImageUrl(
  projectId: string,
  characterId: string,
  imageId: string
): string {
  return `${API_BASE_URL}/api/v1/projects/${projectId}/characters/${characterId}/images/${imageId}/file`;
}

/**
 * Build the URL for a generation panel image
 */
export function generationPanelImageUrl(
  projectId: string,
  boardId: string,
  panelId: string
): string {
  return `${API_BASE_URL}/api/v1/projects/${projectId}/generation/boards/${boardId}/panels/${panelId}/image`;
}
