// This file is auto-generated by @hey-api/openapi-ts

export const AssetDetailSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        checksum: {
            type: 'string',
            title: 'Checksum'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        storage_path: {
            type: 'string',
            title: 'Storage Path'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/AssetStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        },
        links: {
            items: {
                $ref: '#/components/schemas/AssetLinkRead'
            },
            type: 'array',
            title: 'Links'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'slug',
        'name',
        'original_filename',
        'mime_type',
        'checksum',
        'size_bytes',
        'storage_path',
        'description',
        'tags_json',
        'status',
        'created_at',
        'updated_at'
    ],
    title: 'AssetDetail'
} as const;

export const AssetImportSchema = {
    properties: {
        source_path: {
            type: 'string',
            minLength: 1,
            title: 'Source Path'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            type: 'string',
            title: 'Description',
            default: ''
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        }
    },
    type: 'object',
    required: [
        'source_path'
    ],
    title: 'AssetImport'
} as const;

export const AssetLinkCreateSchema = {
    properties: {
        asset_id: {
            type: 'string',
            title: 'Asset Id'
        },
        target_kind: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Target Kind'
        },
        target_id: {
            type: 'string',
            maxLength: 36,
            minLength: 1,
            title: 'Target Id'
        },
        note: {
            type: 'string',
            title: 'Note',
            default: ''
        }
    },
    type: 'object',
    required: [
        'asset_id',
        'target_kind',
        'target_id'
    ],
    title: 'AssetLinkCreate'
} as const;

export const AssetLinkReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        asset_id: {
            type: 'string',
            title: 'Asset Id'
        },
        target_kind: {
            type: 'string',
            title: 'Target Kind'
        },
        target_id: {
            type: 'string',
            title: 'Target Id'
        },
        note: {
            type: 'string',
            title: 'Note'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'asset_id',
        'target_kind',
        'target_id',
        'note',
        'created_at'
    ],
    title: 'AssetLinkRead'
} as const;

export const AssetListResponseSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/AssetRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: [
        'items'
    ],
    title: 'AssetListResponse'
} as const;

export const AssetReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        checksum: {
            type: 'string',
            title: 'Checksum'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        storage_path: {
            type: 'string',
            title: 'Storage Path'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/AssetStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'slug',
        'name',
        'original_filename',
        'mime_type',
        'checksum',
        'size_bytes',
        'storage_path',
        'description',
        'tags_json',
        'status',
        'created_at',
        'updated_at'
    ],
    title: 'AssetRead'
} as const;

export const AssetStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'archived'
    ],
    title: 'AssetStatus'
} as const;

export const AssetUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        tags_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags Json'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/AssetStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'AssetUpdate'
} as const;

export const ChapterCreateSchema = {
    properties: {
        tome_id: {
            type: 'string',
            title: 'Tome Id'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        synopsis: {
            type: 'string',
            title: 'Synopsis',
            default: ''
        },
        status: {
            $ref: '#/components/schemas/StoryStatus',
            default: 'active'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index',
            default: 0
        }
    },
    type: 'object',
    required: [
        'tome_id',
        'title'
    ],
    title: 'ChapterCreate'
} as const;

export const ChapterReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        tome_id: {
            type: 'string',
            title: 'Tome Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        synopsis: {
            type: 'string',
            title: 'Synopsis'
        },
        status: {
            $ref: '#/components/schemas/StoryStatus'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'tome_id',
        'title',
        'slug',
        'synopsis',
        'status',
        'order_index',
        'created_at',
        'updated_at'
    ],
    title: 'ChapterRead'
} as const;

export const ChapterUpdateSchema = {
    properties: {
        tome_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tome Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        synopsis: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Synopsis'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/StoryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        order_index: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order Index'
        }
    },
    type: 'object',
    title: 'ChapterUpdate'
} as const;

export const CharacterCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        narrative_role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Narrative Role'
        },
        description: {
            type: 'string',
            title: 'Description',
            default: ''
        },
        physical_description: {
            type: 'string',
            title: 'Physical Description',
            default: ''
        },
        color_palette_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Color Palette Json'
        },
        costume_elements_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Costume Elements Json'
        },
        key_traits_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Traits Json'
        },
        personality: {
            type: 'string',
            title: 'Personality',
            default: ''
        },
        narrative_arc: {
            type: 'string',
            title: 'Narrative Arc',
            default: ''
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/CharacterStatus',
            default: 'active'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'CharacterCreate'
} as const;

export const CharacterDetailSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        narrative_role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Narrative Role'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        physical_description: {
            type: 'string',
            title: 'Physical Description'
        },
        color_palette_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Color Palette Json'
        },
        costume_elements_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Costume Elements Json'
        },
        key_traits_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Traits Json'
        },
        personality: {
            type: 'string',
            title: 'Personality'
        },
        narrative_arc: {
            type: 'string',
            title: 'Narrative Arc'
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/CharacterStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        },
        relationships_summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relationships Summary'
        },
        relations: {
            items: {
                $ref: '#/components/schemas/CharacterRelationRead'
            },
            type: 'array',
            title: 'Relations'
        },
        voice_samples: {
            items: {
                $ref: '#/components/schemas/VoiceSampleRead'
            },
            type: 'array',
            title: 'Voice Samples'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'slug',
        'name',
        'alias',
        'narrative_role',
        'description',
        'physical_description',
        'color_palette_json',
        'costume_elements_json',
        'key_traits_json',
        'personality',
        'narrative_arc',
        'tags_json',
        'status',
        'created_at',
        'updated_at'
    ],
    title: 'CharacterDetail'
} as const;

export const CharacterDuplicateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'CharacterDuplicate'
} as const;

export const CharacterImageListResponseSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/CharacterImageRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: [
        'items'
    ],
    title: 'CharacterImageListResponse'
} as const;

export const CharacterImageReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        character_id: {
            type: 'string',
            title: 'Character Id'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        file_size: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Size'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        strategy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strategy'
        },
        style: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Style'
        },
        variation_index: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variation Index'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'character_id',
        'file_path',
        'file_name',
        'file_size',
        'mime_type',
        'prompt',
        'strategy',
        'style',
        'variation_index',
        'created_at'
    ],
    title: 'CharacterImageRead'
} as const;

export const CharacterListResponseSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/CharacterRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: [
        'items'
    ],
    title: 'CharacterListResponse'
} as const;

export const CharacterReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        narrative_role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Narrative Role'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        physical_description: {
            type: 'string',
            title: 'Physical Description'
        },
        color_palette_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Color Palette Json'
        },
        costume_elements_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Costume Elements Json'
        },
        key_traits_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Key Traits Json'
        },
        personality: {
            type: 'string',
            title: 'Personality'
        },
        narrative_arc: {
            type: 'string',
            title: 'Narrative Arc'
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/CharacterStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'slug',
        'name',
        'alias',
        'narrative_role',
        'description',
        'physical_description',
        'color_palette_json',
        'costume_elements_json',
        'key_traits_json',
        'personality',
        'narrative_arc',
        'tags_json',
        'status',
        'created_at',
        'updated_at'
    ],
    title: 'CharacterRead'
} as const;

export const CharacterRelationCreateSchema = {
    properties: {
        source_character_id: {
            type: 'string',
            title: 'Source Character Id'
        },
        target_character_id: {
            type: 'string',
            title: 'Target Character Id'
        },
        relation_type: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Relation Type'
        },
        strength: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Strength',
            default: 50
        },
        narrative_dependency: {
            type: 'string',
            title: 'Narrative Dependency',
            default: ''
        },
        notes: {
            type: 'string',
            title: 'Notes',
            default: ''
        }
    },
    type: 'object',
    required: [
        'source_character_id',
        'target_character_id',
        'relation_type'
    ],
    title: 'CharacterRelationCreate'
} as const;

export const CharacterRelationReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        source_character_id: {
            type: 'string',
            title: 'Source Character Id'
        },
        target_character_id: {
            type: 'string',
            title: 'Target Character Id'
        },
        relation_type: {
            type: 'string',
            title: 'Relation Type'
        },
        strength: {
            type: 'integer',
            title: 'Strength'
        },
        narrative_dependency: {
            type: 'string',
            title: 'Narrative Dependency'
        },
        notes: {
            type: 'string',
            title: 'Notes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'source_character_id',
        'target_character_id',
        'relation_type',
        'strength',
        'narrative_dependency',
        'notes',
        'created_at',
        'updated_at'
    ],
    title: 'CharacterRelationRead'
} as const;

export const CharacterRelationUpdateSchema = {
    properties: {
        relation_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relation Type'
        },
        strength: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strength'
        },
        narrative_dependency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Narrative Dependency'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CharacterRelationUpdate'
} as const;

export const CharacterStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'draft',
        'archived'
    ],
    title: 'CharacterStatus'
} as const;

export const CharacterUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        narrative_role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Narrative Role'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        physical_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Physical Description'
        },
        color_palette_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color Palette Json'
        },
        costume_elements_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Costume Elements Json'
        },
        key_traits_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key Traits Json'
        },
        personality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Personality'
        },
        narrative_arc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Narrative Arc'
        },
        tags_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags Json'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/CharacterStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'CharacterUpdate'
} as const;

export const ColorModeSchema = {
    type: 'string',
    enum: [
        'bw',
        'color',
        'spot_color'
    ],
    title: 'ColorMode',
    description: 'Color modes for manga generation.'
} as const;

export const ExportCreateSchema = {
    properties: {
        kind: {
            $ref: '#/components/schemas/ExportKind',
            default: 'work'
        },
        format: {
            $ref: '#/components/schemas/ExportFormat',
            default: 'json'
        },
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        summary: {
            type: 'string',
            maxLength: 2000,
            title: 'Summary',
            default: ''
        }
    },
    type: 'object',
    title: 'ExportCreate'
} as const;

export const ExportFormatSchema = {
    type: 'string',
    enum: [
        'json',
        'tree',
        'zip'
    ],
    title: 'ExportFormat'
} as const;

export const ExportKindSchema = {
    type: 'string',
    enum: [
        'work',
        'publication'
    ],
    title: 'ExportKind'
} as const;

export const ExportReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        kind: {
            $ref: '#/components/schemas/ExportKind'
        },
        format: {
            $ref: '#/components/schemas/ExportFormat'
        },
        status: {
            $ref: '#/components/schemas/ExportStatus'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        artifact_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Artifact Path'
        },
        artifact_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Artifact Name'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        failed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'kind',
        'format',
        'status',
        'label',
        'summary',
        'metadata_json',
        'created_at',
        'updated_at'
    ],
    title: 'ExportRead'
} as const;

export const ExportStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'ready',
        'failed'
    ],
    title: 'ExportStatus'
} as const;

export const GenerationBoardPanelReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        board_id: {
            type: 'string',
            title: 'Board Id'
        },
        step_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Step Id'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        caption: {
            type: 'string',
            title: 'Caption'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        image_path: {
            type: 'string',
            title: 'Image Path'
        },
        image_name: {
            type: 'string',
            title: 'Image Name'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'board_id',
        'step_id',
        'order_index',
        'title',
        'caption',
        'prompt',
        'status',
        'image_path',
        'image_name',
        'metadata_json',
        'created_at',
        'updated_at'
    ],
    title: 'GenerationBoardPanelRead'
} as const;

export const GenerationBoardReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        source_kind: {
            $ref: '#/components/schemas/GenerationSourceKind'
        },
        strategy: {
            type: 'string',
            title: 'Strategy'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        artifact_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Artifact Path'
        },
        artifact_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Artifact Name'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        validated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validated At'
        },
        panels: {
            items: {
                $ref: '#/components/schemas/GenerationBoardPanelRead'
            },
            type: 'array',
            title: 'Panels'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'job_id',
        'source_kind',
        'strategy',
        'title',
        'summary',
        'status',
        'artifact_path',
        'artifact_name',
        'metadata_json',
        'created_at',
        'updated_at',
        'validated_at'
    ],
    title: 'GenerationBoardRead'
} as const;

export const GenerationBoardValidateRequestSchema = {
    properties: {
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    title: 'GenerationBoardValidateRequest'
} as const;

export const GenerationJobCreateSchema = {
    properties: {
        source_kind: {
            $ref: '#/components/schemas/GenerationSourceKind'
        },
        source_id: {
            type: 'string',
            title: 'Source Id'
        },
        source_version_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Version Id'
        },
        strategy: {
            type: 'string',
            title: 'Strategy',
            default: 'direct'
        },
        model_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Key'
        },
        mode: {
            type: 'string',
            title: 'Mode',
            default: 'separate'
        },
        selection_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Selection Ids'
        },
        grid_rows: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grid Rows'
        },
        grid_cols: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grid Cols'
        },
        image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Count'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        summary: {
            type: 'string',
            title: 'Summary',
            default: ''
        }
    },
    type: 'object',
    required: [
        'source_kind',
        'source_id'
    ],
    title: 'GenerationJobCreate'
} as const;

export const GenerationJobReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        source_kind: {
            $ref: '#/components/schemas/GenerationSourceKind'
        },
        source_id: {
            type: 'string',
            title: 'Source Id'
        },
        source_label: {
            type: 'string',
            title: 'Source Label'
        },
        source_version_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Version Id'
        },
        strategy: {
            type: 'string',
            title: 'Strategy'
        },
        model_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Key'
        },
        model_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Name'
        },
        model_kind: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Kind'
        },
        entrypoint: {
            type: 'string',
            title: 'Entrypoint'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            type: 'integer',
            title: 'Progress'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        failed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        steps: {
            items: {
                $ref: '#/components/schemas/GenerationJobStepRead'
            },
            type: 'array',
            title: 'Steps'
        },
        board: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GenerationBoardRead'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'source_kind',
        'source_id',
        'source_label',
        'source_version_id',
        'strategy',
        'entrypoint',
        'title',
        'prompt',
        'summary',
        'status',
        'progress',
        'metadata_json',
        'created_at',
        'updated_at',
        'completed_at',
        'failed_at',
        'error_message'
    ],
    title: 'GenerationJobRead'
} as const;

export const GenerationJobStepReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        output_text: {
            type: 'string',
            title: 'Output Text'
        },
        artifact_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Artifact Path'
        },
        artifact_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Artifact Name'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        failed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed At'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'id',
        'job_id',
        'order_index',
        'title',
        'status',
        'prompt',
        'output_text',
        'artifact_path',
        'artifact_name',
        'metadata_json',
        'created_at',
        'updated_at',
        'completed_at',
        'failed_at',
        'error_message'
    ],
    title: 'GenerationJobStepRead'
} as const;

export const GenerationPanelUpdateSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        caption: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'GenerationPanelUpdate'
} as const;

export const GenerationSourceKindSchema = {
    type: 'string',
    enum: [
        'scene',
        'chapter',
        'tome',
        'panel',
        'custom'
    ],
    title: 'GenerationSourceKind'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ModelProviderReadSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        kind: {
            type: 'string',
            title: 'Kind'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        configured: {
            type: 'boolean',
            title: 'Configured'
        },
        has_api_key: {
            type: 'boolean',
            title: 'Has Api Key'
        }
    },
    type: 'object',
    required: [
        'key',
        'kind',
        'display_name',
        'enabled',
        'configured',
        'has_api_key'
    ],
    title: 'ModelProviderRead'
} as const;

export const ProjectCloneSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'ProjectClone'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        settings_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Settings Json'
        },
        status: {
            $ref: '#/components/schemas/ProjectStatus',
            default: 'draft'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ProjectCreate'
} as const;

export const ProjectListResponseSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ProjectRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: [
        'items'
    ],
    title: 'ProjectListResponse'
} as const;

export const ProjectReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        status: {
            $ref: '#/components/schemas/ProjectStatus'
        },
        root_path: {
            type: 'string',
            title: 'Root Path'
        },
        settings_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Settings Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        last_opened_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Opened At'
        },
        archived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Archived At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'slug',
        'status',
        'root_path',
        'settings_json',
        'created_at',
        'updated_at'
    ],
    title: 'ProjectRead'
} as const;

export const ProjectStatusSchema = {
    type: 'string',
    enum: [
        'draft',
        'active',
        'archived',
        'maintenance'
    ],
    title: 'ProjectStatus'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ProjectStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        settings_json: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Settings Json'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const PromptPreviewRequestSchema = {
    properties: {
        config_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config Id'
        },
        character_image_refs: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Character Image Refs'
        },
        additional_context: {
            type: 'string',
            title: 'Additional Context',
            default: ''
        }
    },
    type: 'object',
    title: 'PromptPreviewRequest',
    description: 'Request to preview the generated prompt without running generation.'
} as const;

export const PromptPreviewResponseSchema = {
    properties: {
        system_prompt: {
            type: 'string',
            title: 'System Prompt'
        },
        scene_section: {
            type: 'string',
            title: 'Scene Section'
        },
        full_prompt: {
            type: 'string',
            title: 'Full Prompt'
        },
        character_summaries: {
            items: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'array',
            title: 'Character Summaries'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        }
    },
    type: 'object',
    required: [
        'system_prompt',
        'scene_section',
        'full_prompt',
        'character_summaries'
    ],
    title: 'PromptPreviewResponse',
    description: 'Preview of the prompt that would be sent.'
} as const;

export const ReferenceSuggestionResponseSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        label: {
            type: 'string',
            title: 'Label'
        }
    },
    type: 'object',
    required: [
        'slug',
        'label'
    ],
    title: 'ReferenceSuggestionResponse'
} as const;

export const SceneCreateSchema = {
    properties: {
        tome_id: {
            type: 'string',
            title: 'Tome Id'
        },
        chapter_id: {
            type: 'string',
            title: 'Chapter Id'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        summary: {
            type: 'string',
            title: 'Summary',
            default: ''
        },
        content: {
            type: 'string',
            title: 'Content',
            default: ''
        },
        notes: {
            type: 'string',
            title: 'Notes',
            default: ''
        },
        characters_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Characters Json'
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/StoryStatus',
            default: 'active'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index',
            default: 0
        }
    },
    type: 'object',
    required: [
        'tome_id',
        'chapter_id',
        'title'
    ],
    title: 'SceneCreate'
} as const;

export const SceneGenerateRequestSchema = {
    properties: {
        config_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config Id'
        },
        image_count: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Image Count',
            default: 1
        },
        style_override: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Style Override',
            description: 'Optional style overrides'
        },
        character_image_refs: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Character Image Refs',
            description: 'Map of character slug to image ID to use as reference'
        },
        additional_context: {
            type: 'string',
            title: 'Additional Context',
            description: 'Additional context to append to the scene description',
            default: ''
        }
    },
    type: 'object',
    title: 'SceneGenerateRequest',
    description: 'Request to generate manga pages from a scene.'
} as const;

export const SceneGenerateResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: 'Generation job started'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'status'
    ],
    title: 'SceneGenerateResponse',
    description: 'Response after triggering generation.'
} as const;

export const SceneGenerationConfigCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        system_prompt: {
            type: 'string',
            minLength: 10,
            title: 'System Prompt'
        },
        style_preset: {
            $ref: '#/components/schemas/StylePreset',
            default: 'generic'
        },
        color_mode: {
            $ref: '#/components/schemas/ColorMode',
            default: 'bw'
        },
        default_image_count: {
            type: 'integer',
            maximum: 10,
            minimum: 1,
            title: 'Default Image Count',
            default: 1
        },
        allow_multi_page: {
            type: 'boolean',
            title: 'Allow Multi Page',
            default: true
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        }
    },
    type: 'object',
    required: [
        'name',
        'system_prompt'
    ],
    title: 'SceneGenerationConfigCreate',
    description: 'Create a new generation config.'
} as const;

export const SceneGenerationConfigReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default'
        },
        system_prompt: {
            type: 'string',
            title: 'System Prompt'
        },
        style_preset: {
            type: 'string',
            title: 'Style Preset'
        },
        color_mode: {
            type: 'string',
            title: 'Color Mode'
        },
        default_image_count: {
            type: 'integer',
            title: 'Default Image Count'
        },
        allow_multi_page: {
            type: 'boolean',
            title: 'Allow Multi Page'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'name',
        'is_default',
        'system_prompt',
        'style_preset',
        'color_mode',
        'default_image_count',
        'allow_multi_page',
        'metadata_json',
        'created_at',
        'updated_at'
    ],
    title: 'SceneGenerationConfigRead',
    description: 'Config read model.'
} as const;

export const SceneGenerationConfigUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Default'
        },
        system_prompt: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'System Prompt'
        },
        style_preset: {
            anyOf: [
                {
                    $ref: '#/components/schemas/StylePreset'
                },
                {
                    type: 'null'
                }
            ]
        },
        color_mode: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ColorMode'
                },
                {
                    type: 'null'
                }
            ]
        },
        default_image_count: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Image Count'
        },
        allow_multi_page: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Allow Multi Page'
        },
        metadata_json: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        }
    },
    type: 'object',
    title: 'SceneGenerationConfigUpdate',
    description: 'Update an existing config.'
} as const;

export const SceneGenerationListResponseSchema = {
    properties: {
        scene_id: {
            type: 'string',
            title: 'Scene Id'
        },
        pages: {
            items: {
                $ref: '#/components/schemas/SceneMangaPageRead'
            },
            type: 'array',
            title: 'Pages'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'scene_id',
        'pages',
        'total_pages'
    ],
    title: 'SceneGenerationListResponse',
    description: 'List of generation jobs for a scene.'
} as const;

export const SceneMangaPageReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        scene_id: {
            type: 'string',
            title: 'Scene Id'
        },
        tome_id: {
            type: 'string',
            title: 'Tome Id'
        },
        chapter_id: {
            type: 'string',
            title: 'Chapter Id'
        },
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        board_id: {
            type: 'string',
            title: 'Board Id'
        },
        panel_id: {
            type: 'string',
            title: 'Panel Id'
        },
        page_number: {
            type: 'integer',
            title: 'Page Number'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        caption: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption'
        },
        prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prompt'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'scene_id',
        'tome_id',
        'chapter_id',
        'job_id',
        'board_id',
        'panel_id',
        'page_number',
        'label',
        'status',
        'created_at',
        'updated_at'
    ],
    title: 'SceneMangaPageRead',
    description: 'Read model for a scene manga page.'
} as const;

export const SceneMangaPageUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'draft',
                        'selected',
                        'rejected'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'SceneMangaPageUpdate',
    description: 'Update page metadata.'
} as const;

export const SceneReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        tome_id: {
            type: 'string',
            title: 'Tome Id'
        },
        chapter_id: {
            type: 'string',
            title: 'Chapter Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        notes: {
            type: 'string',
            title: 'Notes'
        },
        characters_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Characters Json'
        },
        tags_json: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags Json'
        },
        status: {
            $ref: '#/components/schemas/StoryStatus'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'tome_id',
        'chapter_id',
        'title',
        'slug',
        'summary',
        'content',
        'notes',
        'characters_json',
        'tags_json',
        'status',
        'order_index',
        'created_at',
        'updated_at'
    ],
    title: 'SceneRead'
} as const;

export const SceneUpdateSchema = {
    properties: {
        tome_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tome Id'
        },
        chapter_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chapter Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        characters_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Characters Json'
        },
        tags_json: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags Json'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/StoryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        order_index: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order Index'
        }
    },
    type: 'object',
    title: 'SceneUpdate'
} as const;

export const StoryOrphanReferenceReadSchema = {
    properties: {
        reference: {
            $ref: '#/components/schemas/StoryReferenceRead'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        }
    },
    type: 'object',
    required: [
        'reference',
        'reason'
    ],
    title: 'StoryOrphanReferenceRead'
} as const;

export const StoryReferenceReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        scene_id: {
            type: 'string',
            title: 'Scene Id'
        },
        reference_kind: {
            type: 'string',
            title: 'Reference Kind'
        },
        target_slug: {
            type: 'string',
            title: 'Target Slug'
        },
        raw_token: {
            type: 'string',
            title: 'Raw Token'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'scene_id',
        'reference_kind',
        'target_slug',
        'raw_token',
        'created_at'
    ],
    title: 'StoryReferenceRead'
} as const;

export const StoryStatusSchema = {
    type: 'string',
    enum: [
        'active',
        'draft',
        'archived'
    ],
    title: 'StoryStatus'
} as const;

export const StorySuggestionReadSchema = {
    properties: {
        kind: {
            type: 'string',
            title: 'Kind'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        label: {
            type: 'string',
            title: 'Label'
        }
    },
    type: 'object',
    required: [
        'kind',
        'slug',
        'title',
        'label'
    ],
    title: 'StorySuggestionRead'
} as const;

export const StorySummaryResponseSchema = {
    properties: {
        tomes: {
            items: {
                $ref: '#/components/schemas/TomeRead'
            },
            type: 'array',
            title: 'Tomes'
        },
        chapters: {
            items: {
                $ref: '#/components/schemas/ChapterRead'
            },
            type: 'array',
            title: 'Chapters'
        },
        scenes: {
            items: {
                $ref: '#/components/schemas/SceneRead'
            },
            type: 'array',
            title: 'Scenes'
        },
        orphan_references: {
            items: {
                $ref: '#/components/schemas/StoryOrphanReferenceRead'
            },
            type: 'array',
            title: 'Orphan References'
        }
    },
    type: 'object',
    required: [
        'tomes',
        'chapters',
        'scenes'
    ],
    title: 'StorySummaryResponse'
} as const;

export const StylePresetSchema = {
    type: 'string',
    enum: [
        'shonen',
        'shojo',
        'seinen',
        'generic'
    ],
    title: 'StylePreset',
    description: 'Manga style presets.'
} as const;

export const TomeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        synopsis: {
            type: 'string',
            title: 'Synopsis',
            default: ''
        },
        status: {
            $ref: '#/components/schemas/StoryStatus',
            default: 'active'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index',
            default: 0
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'TomeCreate'
} as const;

export const TomeReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        synopsis: {
            type: 'string',
            title: 'Synopsis'
        },
        status: {
            $ref: '#/components/schemas/StoryStatus'
        },
        order_index: {
            type: 'integer',
            title: 'Order Index'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'title',
        'slug',
        'synopsis',
        'status',
        'order_index',
        'created_at',
        'updated_at'
    ],
    title: 'TomeRead'
} as const;

export const TomeUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        synopsis: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Synopsis'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/StoryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        order_index: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order Index'
        }
    },
    type: 'object',
    title: 'TomeUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VersionBranchReadSchema = {
    properties: {
        branch_name: {
            type: 'string',
            title: 'Branch Name'
        },
        version_count: {
            type: 'integer',
            title: 'Version Count'
        },
        latest_version_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version Id'
        },
        latest_created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Created At'
        }
    },
    type: 'object',
    required: [
        'branch_name',
        'version_count'
    ],
    title: 'VersionBranchRead'
} as const;

export const VersionCompareReadSchema = {
    properties: {
        left: {
            $ref: '#/components/schemas/VersionRead'
        },
        right: {
            $ref: '#/components/schemas/VersionRead'
        },
        project_changes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Project Changes'
        },
        counts_delta: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Counts Delta'
        }
    },
    type: 'object',
    required: [
        'left',
        'right'
    ],
    title: 'VersionCompareRead'
} as const;

export const VersionCompareRequestSchema = {
    properties: {
        left_version_id: {
            type: 'string',
            title: 'Left Version Id'
        },
        right_version_id: {
            type: 'string',
            title: 'Right Version Id'
        }
    },
    type: 'object',
    required: [
        'left_version_id',
        'right_version_id'
    ],
    title: 'VersionCompareRequest'
} as const;

export const VersionCreateSchema = {
    properties: {
        branch_name: {
            type: 'string',
            maxLength: 255,
            title: 'Branch Name',
            default: 'main'
        },
        label: {
            type: 'string',
            maxLength: 255,
            title: 'Label',
            default: 'Checkpoint'
        },
        summary: {
            type: 'string',
            title: 'Summary',
            default: ''
        }
    },
    type: 'object',
    title: 'VersionCreate'
} as const;

export const VersionReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        branch_name: {
            type: 'string',
            title: 'Branch Name'
        },
        version_index: {
            type: 'integer',
            title: 'Version Index'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'branch_name',
        'version_index',
        'label',
        'summary',
        'created_at'
    ],
    title: 'VersionRead'
} as const;

export const VersionRestoreRequestSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        }
    },
    type: 'object',
    title: 'VersionRestoreRequest'
} as const;

export const VoiceSampleCreateSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Label'
        },
        asset_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asset Path'
        },
        voice_notes: {
            type: 'string',
            title: 'Voice Notes',
            default: ''
        }
    },
    type: 'object',
    required: [
        'label'
    ],
    title: 'VoiceSampleCreate'
} as const;

export const VoiceSampleReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        character_id: {
            type: 'string',
            title: 'Character Id'
        },
        asset_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Asset Path'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        voice_notes: {
            type: 'string',
            title: 'Voice Notes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'character_id',
        'asset_path',
        'label',
        'voice_notes',
        'created_at'
    ],
    title: 'VoiceSampleRead'
} as const;

export const WarningKindSchema = {
    type: 'string',
    enum: [
        'missing_character_reference',
        'timeline_incoherence',
        'orphan_reference',
        'orphan_character_image'
    ],
    title: 'WarningKind'
} as const;

export const WarningReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            title: 'Project Id'
        },
        fingerprint: {
            type: 'string',
            title: 'Fingerprint'
        },
        kind: {
            $ref: '#/components/schemas/WarningKind'
        },
        severity: {
            $ref: '#/components/schemas/WarningSeverity'
        },
        status: {
            $ref: '#/components/schemas/WarningStatus'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        entity_kind: {
            type: 'string',
            title: 'Entity Kind'
        },
        entity_id: {
            type: 'string',
            title: 'Entity Id'
        },
        metadata_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Metadata Json'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        resolved_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolved At'
        }
    },
    type: 'object',
    required: [
        'id',
        'project_id',
        'fingerprint',
        'kind',
        'severity',
        'status',
        'title',
        'message',
        'entity_kind',
        'entity_id',
        'metadata_json',
        'created_at',
        'updated_at'
    ],
    title: 'WarningRead'
} as const;

export const WarningScanResponseSchema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/WarningRead'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: [
        'items'
    ],
    title: 'WarningScanResponse'
} as const;

export const WarningSeveritySchema = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'critical'
    ],
    title: 'WarningSeverity'
} as const;

export const WarningStatusSchema = {
    type: 'string',
    enum: [
        'open',
        'ignored',
        'resolved'
    ],
    title: 'WarningStatus'
} as const;

export const WarningUpdateSchema = {
    properties: {
        status: {
            $ref: '#/components/schemas/WarningStatus'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: [
        'status'
    ],
    title: 'WarningUpdate'
} as const;
