// This file is auto-generated by @hey-api/openapi-ts

export const ProjectSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        slug: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'draft',
                'active',
                'archived',
                'maintenance'
            ]
        },
        rootPath: {
            type: 'string'
        },
        settingsJson: {
            type: 'object',
            propertyNames: {
                type: 'string'
            },
            additionalProperties: {}
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
        },
        lastOpenedAt: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time',
                    pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
                },
                {
                    type: 'null'
                }
            ]
        },
        archivedAt: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time',
                    pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    required: [
        'id',
        'name',
        'slug',
        'status',
        'rootPath',
        'settingsJson',
        'createdAt',
        'updatedAt',
        'lastOpenedAt',
        'archivedAt'
    ],
    additionalProperties: false
} as const;

export const ProjectListSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'array',
    items: {
        type: 'object',
        properties: {
            id: {
                type: 'string'
            },
            name: {
                type: 'string'
            },
            slug: {
                type: 'string'
            },
            status: {
                type: 'string',
                enum: [
                    'draft',
                    'active',
                    'archived',
                    'maintenance'
                ]
            },
            rootPath: {
                type: 'string'
            },
            settingsJson: {
                type: 'object',
                propertyNames: {
                    type: 'string'
                },
                additionalProperties: {}
            },
            createdAt: {
                type: 'string',
                format: 'date-time',
                pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
            },
            updatedAt: {
                type: 'string',
                format: 'date-time',
                pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
            },
            lastOpenedAt: {
                anyOf: [
                    {
                        type: 'string',
                        format: 'date-time',
                        pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
                    },
                    {
                        type: 'null'
                    }
                ]
            },
            archivedAt: {
                anyOf: [
                    {
                        type: 'string',
                        format: 'date-time',
                        pattern: '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
                    },
                    {
                        type: 'null'
                    }
                ]
            }
        },
        required: [
            'id',
            'name',
            'slug',
            'status',
            'rootPath',
            'settingsJson',
            'createdAt',
            'updatedAt',
            'lastOpenedAt',
            'archivedAt'
        ],
        additionalProperties: false
    }
} as const;
