// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type Project = {
    id: string;
    name: string;
    slug: string;
    status: 'draft' | 'active' | 'archived' | 'maintenance';
    rootPath: string;
    settingsJson: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
    lastOpenedAt: string | unknown;
    archivedAt: string | unknown;
};

export type ProjectList = Array<{
    id: string;
    name: string;
    slug: string;
    status: 'draft' | 'active' | 'archived' | 'maintenance';
    rootPath: string;
    settingsJson: {
        [key: string]: unknown;
    };
    createdAt: string;
    updatedAt: string;
    lastOpenedAt: string | unknown;
    archivedAt: string | unknown;
}>;

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Response for status 200
     */
    200: {
        status: string;
        service: string;
        version: string;
        timestamp: string;
        dataDir: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/healthz';
};

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigResponses = {
    /**
     * Response for status 200
     */
    200: {
        appName: string;
        appVersion: string;
        environment: string;
        locale: string;
        dataDir: string;
        projectDataDir: string;
        exportsDir: string;
        openapiUrl: string;
    };
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type ListModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/models';
};

export type ListModelsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        key: string;
        kind: 'image' | 'video' | 'audio';
        displayName: string;
        baseUrl: string | unknown;
        enabled: boolean;
        configured: boolean;
        hasApiKey: boolean;
    }>;
};

export type ListModelsResponse = ListModelsResponses[keyof ListModelsResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type ListProjectsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    }>;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: {
        name: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        settingsJson?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type CreateProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    };
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body: {
        confirmedName: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}';
};

export type DeleteProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        jobId: string;
        status: string;
    };
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}';
};

export type GetProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    };
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: {
        name?: string;
        status?: 'draft' | 'active' | 'archived' | 'maintenance';
        settingsJson?: {
            [key: string]: unknown;
        };
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}';
};

export type UpdateProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    };
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type OpenProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/open';
};

export type OpenProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    };
};

export type OpenProjectResponse = OpenProjectResponses[keyof OpenProjectResponses];

export type ArchiveProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/archive';
};

export type ArchiveProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    };
};

export type ArchiveProjectResponse = ArchiveProjectResponses[keyof ArchiveProjectResponses];

export type CloneProjectData = {
    body: {
        name?: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/clone';
};

export type CloneProjectResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        name: string;
        slug: string;
        status: 'draft' | 'active' | 'archived' | 'maintenance';
        rootPath: string;
        settingsJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        lastOpenedAt: string | unknown;
        archivedAt: string | unknown;
    };
};

export type CloneProjectResponse = CloneProjectResponses[keyof CloneProjectResponses];

export type ExportProjectData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/export';
};

export type ListCharactersData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/';
};

export type ListCharactersResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        slug: string;
        name: string;
        alias: string | unknown;
        narrativeRole: string | unknown;
        description: string;
        physicalDescription: string;
        colorPaletteJson: Array<string>;
        costumeElementsJson: Array<string>;
        keyTraitsJson: Array<string>;
        personality: string;
        narrativeArc: string;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    }>;
};

export type ListCharactersResponse = ListCharactersResponses[keyof ListCharactersResponses];

export type CreateCharacterData = {
    body: {
        name: string;
        alias?: string;
        narrativeRole?: string;
        description?: string;
        physicalDescription?: string;
        colorPaletteJson?: Array<string>;
        costumeElementsJson?: Array<string>;
        keyTraitsJson?: Array<string>;
        personality?: string;
        narrativeArc?: string;
        tagsJson?: Array<string>;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/';
};

export type CreateCharacterResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        alias: string | unknown;
        narrativeRole: string | unknown;
        description: string;
        physicalDescription: string;
        colorPaletteJson: Array<string>;
        costumeElementsJson: Array<string>;
        keyTraitsJson: Array<string>;
        personality: string;
        narrativeArc: string;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    };
};

export type CreateCharacterResponse = CreateCharacterResponses[keyof CreateCharacterResponses];

export type GetProjectCharacterImagesData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/images';
};

export type GetProjectCharacterImagesResponses = {
    /**
     * Response for status 200
     */
    200: {
        [key: string]: Array<{
            id: string;
            projectId: string;
            characterId: string;
            filePath: string;
            fileName: string;
            fileSize: number | unknown;
            mimeType: string;
            prompt: string;
            strategy: string | unknown;
            style: string | unknown;
            variationIndex: number | unknown;
            createdAt: string;
        }>;
    };
};

export type GetProjectCharacterImagesResponse = GetProjectCharacterImagesResponses[keyof GetProjectCharacterImagesResponses];

export type DeleteCharacterData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}';
};

export type GetCharacterData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}';
};

export type GetCharacterResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        alias: string | unknown;
        narrativeRole: string | unknown;
        description: string;
        physicalDescription: string;
        colorPaletteJson: Array<string>;
        costumeElementsJson: Array<string>;
        keyTraitsJson: Array<string>;
        personality: string;
        narrativeArc: string;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
        relations: Array<{
            id: string;
            projectId: string;
            sourceCharacterId: string;
            targetCharacterId: string;
            relationType: string;
            strength: number;
            narrativeDependency: string;
            notes: string;
            createdAt: string;
            updatedAt: string;
        }>;
        voiceSamples: Array<{
            id: string;
            projectId: string;
            characterId: string;
            assetPath: string | unknown;
            label: string;
            voiceNotes: string;
            createdAt: string;
        }>;
        relationshipsSummary: string | unknown;
    };
};

export type GetCharacterResponse = GetCharacterResponses[keyof GetCharacterResponses];

export type UpdateCharacterData = {
    body: {
        name?: string;
        alias?: string;
        narrativeRole?: string;
        description?: string;
        physicalDescription?: string;
        colorPaletteJson?: Array<string>;
        costumeElementsJson?: Array<string>;
        keyTraitsJson?: Array<string>;
        personality?: string;
        narrativeArc?: string;
        tagsJson?: Array<string>;
        status?: 'active' | 'draft' | 'archived';
    };
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}';
};

export type UpdateCharacterResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        alias: string | unknown;
        narrativeRole: string | unknown;
        description: string;
        physicalDescription: string;
        colorPaletteJson: Array<string>;
        costumeElementsJson: Array<string>;
        keyTraitsJson: Array<string>;
        personality: string;
        narrativeArc: string;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    };
};

export type UpdateCharacterResponse = UpdateCharacterResponses[keyof UpdateCharacterResponses];

export type ArchiveCharacterData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}/archive';
};

export type ArchiveCharacterResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        alias: string | unknown;
        narrativeRole: string | unknown;
        description: string;
        physicalDescription: string;
        colorPaletteJson: Array<string>;
        costumeElementsJson: Array<string>;
        keyTraitsJson: Array<string>;
        personality: string;
        narrativeArc: string;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    };
};

export type ArchiveCharacterResponse = ArchiveCharacterResponses[keyof ArchiveCharacterResponses];

export type CreateRelationData = {
    body: {
        sourceCharacterId: string;
        targetCharacterId: string;
        relationType: string;
        strength: number;
        narrativeDependency?: string;
        notes?: string;
    };
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}/relations';
};

export type CreateRelationResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        sourceCharacterId: string;
        targetCharacterId: string;
        relationType: string;
        strength: number;
        narrativeDependency: string;
        notes: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateRelationResponse = CreateRelationResponses[keyof CreateRelationResponses];

export type CreateVoiceSampleData = {
    body: {
        sourceCharacterId: string;
        targetCharacterId: string;
        relationType: string;
        strength: number;
        narrativeDependency?: string;
        notes?: string;
    };
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}/voice-samples';
};

export type CreateVoiceSampleResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        characterId: string;
        assetPath: string | unknown;
        label: string;
        voiceNotes: string;
        createdAt: string;
    };
};

export type CreateVoiceSampleResponse = CreateVoiceSampleResponses[keyof CreateVoiceSampleResponses];

export type GenerateCharacterImageData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
    };
    query: {
        strategy: string;
        style: string;
        imageCount: number;
        modelKey?: string;
    };
    url: '/api/projects/{projectId}/characters/{characterId}/generate-image';
};

export type ListCharacterImagesData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}/images';
};

export type ListCharacterImagesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        characterId: string;
        filePath: string;
        fileName: string;
        fileSize: number | unknown;
        mimeType: string;
        prompt: string;
        strategy: string | unknown;
        style: string | unknown;
        variationIndex: number | unknown;
        createdAt: string;
    }>;
};

export type ListCharacterImagesResponse = ListCharacterImagesResponses[keyof ListCharacterImagesResponses];

export type DeleteCharacterImageData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
        imageId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}/images/{imageId}';
};

export type GetCharacterImageFileData = {
    body?: never;
    path: {
        projectId: string;
        characterId: string;
        imageId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/characters/{characterId}/images/{imageId}/file';
};

export type GetStorySummaryData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story';
};

export type GetStorySummaryResponses = {
    /**
     * Response for status 200
     */
    200: {
        tomes: Array<{
            id: string;
            projectId: string;
            title: string;
            slug: string;
            synopsis: string;
            status: 'active' | 'draft' | 'archived';
            orderIndex: number;
            createdAt: string;
            updatedAt: string;
        }>;
        chapters: Array<{
            id: string;
            projectId: string;
            tomeId: string;
            title: string;
            slug: string;
            synopsis: string;
            status: 'active' | 'draft' | 'archived';
            orderIndex: number;
            createdAt: string;
            updatedAt: string;
        }>;
        scenes: Array<{
            id: string;
            projectId: string;
            tomeId: string;
            chapterId: string;
            title: string;
            slug: string;
            sceneType: string;
            location: string;
            summary: string;
            content: string;
            notes: string;
            charactersJson: Array<string>;
            tagsJson: Array<string>;
            status: 'active' | 'draft' | 'archived';
            orderIndex: number;
            createdAt: string;
            updatedAt: string;
        }>;
        orphanReferences: Array<{
            reference: {
                id: string;
                projectId: string;
                sceneId: string;
                referenceKind: string;
                targetSlug: string;
                rawToken: string;
                createdAt: string;
            };
            reason: string;
        }>;
    };
};

export type GetStorySummaryResponse = GetStorySummaryResponses[keyof GetStorySummaryResponses];

export type GetReferenceSuggestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/references/{type}';
};

export type ListTomesData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/tomes';
};

export type CreateTomeData = {
    body: {
        title: string;
        synopsis?: string;
        status?: 'active' | 'draft' | 'archived';
        orderIndex?: number;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/tomes';
};

export type CreateTomeResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        title: string;
        slug: string;
        synopsis: string;
        status: 'active' | 'draft' | 'archived';
        orderIndex: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateTomeResponse = CreateTomeResponses[keyof CreateTomeResponses];

export type DeleteTomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/tomes/{tomeId}';
};

export type UpdateTomeData = {
    body: {
        title?: string;
        synopsis?: string;
        status?: 'active' | 'draft' | 'archived';
        orderIndex?: number;
    };
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/tomes/{tomeId}';
};

export type UpdateTomeResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        title: string;
        slug: string;
        synopsis: string;
        status: 'active' | 'draft' | 'archived';
        orderIndex: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateTomeResponse = UpdateTomeResponses[keyof UpdateTomeResponses];

export type ListChaptersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/chapters';
};

export type CreateChapterData = {
    body: {
        tomeId: string;
        title: string;
        synopsis?: string;
        status?: 'active' | 'draft' | 'archived';
        orderIndex?: number;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/chapters';
};

export type CreateChapterResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        tomeId: string;
        title: string;
        slug: string;
        synopsis: string;
        status: 'active' | 'draft' | 'archived';
        orderIndex: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateChapterResponse = CreateChapterResponses[keyof CreateChapterResponses];

export type DeleteChapterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/chapters/{chapterId}';
};

export type UpdateChapterData = {
    body: {
        tomeId?: string;
        title?: string;
        synopsis?: string;
        status?: 'active' | 'draft' | 'archived';
        orderIndex?: number;
    };
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/chapters/{chapterId}';
};

export type UpdateChapterResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        tomeId: string;
        title: string;
        slug: string;
        synopsis: string;
        status: 'active' | 'draft' | 'archived';
        orderIndex: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateChapterResponse = UpdateChapterResponses[keyof UpdateChapterResponses];

export type ListScenesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/scenes';
};

export type CreateSceneData = {
    body: {
        tomeId: string;
        chapterId: string;
        title: string;
        sceneType?: string;
        location?: string;
        summary?: string;
        content?: string;
        notes?: string;
        charactersJson?: Array<string>;
        tagsJson?: Array<string>;
        status?: 'active' | 'draft' | 'archived';
        orderIndex?: number;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes';
};

export type CreateSceneResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        tomeId: string;
        chapterId: string;
        title: string;
        slug: string;
        sceneType: string;
        location: string;
        summary: string;
        content: string;
        notes: string;
        charactersJson: Array<string>;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        orderIndex: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateSceneResponse = CreateSceneResponses[keyof CreateSceneResponses];

export type DeleteSceneData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}';
};

export type UpdateSceneData = {
    body: {
        tomeId?: string;
        chapterId?: string;
        title?: string;
        sceneType?: string;
        location?: string;
        summary?: string;
        content?: string;
        notes?: string;
        charactersJson?: Array<string>;
        tagsJson?: Array<string>;
        status?: 'active' | 'draft' | 'archived';
        orderIndex?: number;
    };
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}';
};

export type UpdateSceneResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        tomeId: string;
        chapterId: string;
        title: string;
        slug: string;
        sceneType: string;
        location: string;
        summary: string;
        content: string;
        notes: string;
        charactersJson: Array<string>;
        tagsJson: Array<string>;
        status: 'active' | 'draft' | 'archived';
        orderIndex: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateSceneResponse = UpdateSceneResponses[keyof UpdateSceneResponses];

export type ListGenerationJobsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/generation/jobs';
};

export type CreateGenerationJobData = {
    body: {
        sourceKind: 'scene' | 'chapter' | 'tome' | 'panel' | 'custom';
        sourceId: string;
        sourceVersionId?: string;
        strategy: 'direct' | 'intermediate';
        modelKey?: string;
        mode?: string;
        selectionIds?: Array<string>;
        gridRows?: number;
        gridCols?: number;
        imageCount?: number;
        title?: string;
        summary?: string;
    };
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/jobs';
};

export type CreateGenerationJobResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        sourceKind: 'scene' | 'chapter' | 'tome' | 'panel' | 'custom';
        sourceId: string;
        sourceLabel: string;
        sourceVersionId: string | unknown;
        strategy: 'direct' | 'intermediate';
        entrypoint: string;
        title: string;
        prompt: string;
        summary: string;
        status: 'pending' | 'running' | 'ready' | 'validated' | 'failed';
        progress: number;
        metadataJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        completedAt: string | unknown;
        failedAt: string | unknown;
        errorMessage: string | unknown;
    };
};

export type CreateGenerationJobResponse = CreateGenerationJobResponses[keyof CreateGenerationJobResponses];

export type GetGenerationJobData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/jobs/{jobId}';
};

export type GetGenerationJobResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        sourceKind: 'scene' | 'chapter' | 'tome' | 'panel' | 'custom';
        sourceId: string;
        sourceLabel: string;
        sourceVersionId: string | unknown;
        strategy: 'direct' | 'intermediate';
        entrypoint: string;
        title: string;
        prompt: string;
        summary: string;
        status: 'pending' | 'running' | 'ready' | 'validated' | 'failed';
        progress: number;
        metadataJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        completedAt: string | unknown;
        failedAt: string | unknown;
        errorMessage: string | unknown;
    };
};

export type GetGenerationJobResponse = GetGenerationJobResponses[keyof GetGenerationJobResponses];

export type ListGenerationBoardsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/generation/boards';
};

export type GetGenerationBoardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/boards/{boardId}';
};

export type GetGenerationBoardResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        jobId: string;
        sourceKind: 'scene' | 'chapter' | 'tome' | 'panel' | 'custom';
        strategy: 'direct' | 'intermediate';
        title: string;
        summary: string;
        status: 'draft' | 'validated';
        artifactPath: string | unknown;
        artifactName: string | unknown;
        metadataJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        validatedAt: string | unknown;
        panels: Array<{
            id: string;
            boardId: string;
            stepId: string | unknown;
            orderIndex: number;
            title: string;
            caption: string;
            prompt: string;
            status: 'draft' | 'selected' | 'rejected' | 'replaced';
            imagePath: string;
            imageName: string;
            metadataJson: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type GetGenerationBoardResponse = GetGenerationBoardResponses[keyof GetGenerationBoardResponses];

export type ValidateGenerationBoardData = {
    body: {
        note?: string;
    };
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/boards/{boardId}/validate';
};

export type ValidateGenerationBoardResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        jobId: string;
        sourceKind: 'scene' | 'chapter' | 'tome' | 'panel' | 'custom';
        strategy: 'direct' | 'intermediate';
        title: string;
        summary: string;
        status: 'draft' | 'validated';
        artifactPath: string | unknown;
        artifactName: string | unknown;
        metadataJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        validatedAt: string | unknown;
        panels: Array<{
            id: string;
            boardId: string;
            stepId: string | unknown;
            orderIndex: number;
            title: string;
            caption: string;
            prompt: string;
            status: 'draft' | 'selected' | 'rejected' | 'replaced';
            imagePath: string;
            imageName: string;
            metadataJson: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
        }>;
    };
};

export type ValidateGenerationBoardResponse = ValidateGenerationBoardResponses[keyof ValidateGenerationBoardResponses];

export type UpdateGenerationPanelData = {
    body: {
        status?: 'draft' | 'selected' | 'rejected' | 'replaced';
        caption?: string;
        title?: string;
    };
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/boards/{boardId}/panels/{panelId}';
};

export type GetGenerationPanelImageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/boards/{boardId}/panels/{panelId}/image';
};

export type DownloadBoardArtifactData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{projectId}/generation/boards/{boardId}/download';
};

export type ListAssetsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/';
};

export type ListAssetsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        slug: string;
        name: string;
        originalFilename: string;
        mimeType: string;
        checksum: string;
        sizeBytes: number;
        storagePath: string;
        description: string;
        tags: Array<string>;
        status: 'active' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    }>;
};

export type ListAssetsResponse = ListAssetsResponses[keyof ListAssetsResponses];

export type ImportAssetData = {
    body: {
        name: string;
        slug: string;
        sourcePath: string;
        description?: string;
        tags?: Array<string>;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/import';
};

export type ImportAssetResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        originalFilename: string;
        mimeType: string;
        checksum: string;
        sizeBytes: number;
        storagePath: string;
        description: string;
        tags: Array<string>;
        status: 'active' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    };
};

export type ImportAssetResponse = ImportAssetResponses[keyof ImportAssetResponses];

export type DeleteAssetData = {
    body?: never;
    path: {
        projectId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}';
};

export type GetAssetData = {
    body?: never;
    path: {
        projectId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}';
};

export type GetAssetResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        originalFilename: string;
        mimeType: string;
        checksum: string;
        sizeBytes: number;
        storagePath: string;
        description: string;
        tags: Array<string>;
        status: 'active' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
        links: Array<{
            id: string;
            projectId: string;
            assetId: string;
            targetKind: string;
            targetId: string;
            note: string;
            createdAt: string;
        }>;
        usages: Array<{
            kind: string;
            id: string;
            name: string;
        }>;
    };
};

export type GetAssetResponse = GetAssetResponses[keyof GetAssetResponses];

export type UpdateAssetData = {
    body: {
        name?: string;
        description?: string;
        tags?: Array<string>;
    };
    path: {
        projectId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}';
};

export type UpdateAssetResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        originalFilename: string;
        mimeType: string;
        checksum: string;
        sizeBytes: number;
        storagePath: string;
        description: string;
        tags: Array<string>;
        status: 'active' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    };
};

export type UpdateAssetResponse = UpdateAssetResponses[keyof UpdateAssetResponses];

export type ArchiveAssetData = {
    body?: never;
    path: {
        projectId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}/archive';
};

export type ArchiveAssetResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        slug: string;
        name: string;
        originalFilename: string;
        mimeType: string;
        checksum: string;
        sizeBytes: number;
        storagePath: string;
        description: string;
        tags: Array<string>;
        status: 'active' | 'archived';
        createdAt: string;
        updatedAt: string;
        archivedAt: string | unknown;
    };
};

export type ArchiveAssetResponse = ArchiveAssetResponses[keyof ArchiveAssetResponses];

export type GetAssetFileData = {
    body?: never;
    path: {
        projectId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}/file';
};

export type CreateAssetLinkData = {
    body: {
        targetKind: 'character' | 'scene' | 'chapter' | 'tome';
        targetId: string;
        note?: string;
    };
    path: {
        projectId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}/links';
};

export type CreateAssetLinkResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        assetId: string;
        targetKind: string;
        targetId: string;
        note: string;
        createdAt: string;
    };
};

export type CreateAssetLinkResponse = CreateAssetLinkResponses[keyof CreateAssetLinkResponses];

export type DeleteAssetLinkData = {
    body?: never;
    path: {
        projectId: string;
        assetId: string;
        linkId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/assets/{assetId}/links/{linkId}';
};

export type ListSceneConfigsData = {
    body?: never;
    path: {
        projectId: string;
        sceneId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/generation-configs';
};

export type ListSceneConfigsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        name: string;
        isDefault: boolean;
        systemPrompt: string;
        stylePreset: 'shonen' | 'shojo' | 'seinen' | 'generic';
        colorMode: 'bw' | 'color' | 'spot_color';
        defaultImageCount: number;
        allowMultiPage: boolean;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    }>;
};

export type ListSceneConfigsResponse = ListSceneConfigsResponses[keyof ListSceneConfigsResponses];

export type CreateSceneConfigData = {
    body: {
        name: string;
        systemPrompt: string;
        stylePreset: 'shonen' | 'shojo' | 'seinen' | 'generic';
        colorMode: 'bw' | 'color' | 'spot_color';
        defaultImageCount: number;
        allowMultiPage: boolean;
    };
    path: {
        projectId: string;
        sceneId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/generation-configs';
};

export type CreateSceneConfigResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        name: string;
        isDefault: boolean;
        systemPrompt: string;
        stylePreset: 'shonen' | 'shojo' | 'seinen' | 'generic';
        colorMode: 'bw' | 'color' | 'spot_color';
        defaultImageCount: number;
        allowMultiPage: boolean;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateSceneConfigResponse = CreateSceneConfigResponses[keyof CreateSceneConfigResponses];

export type DeleteSceneConfigData = {
    body?: never;
    path: {
        projectId: string;
        sceneId: string;
        configId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/generation-configs/{configId}';
};

export type UpdateSceneConfigData = {
    body: {
        name?: string;
        systemPrompt?: string;
        stylePreset?: 'shonen' | 'shojo' | 'seinen' | 'generic';
        colorMode?: 'bw' | 'color' | 'spot_color';
        defaultImageCount?: number;
        allowMultiPage?: boolean;
    };
    path: {
        projectId: string;
        sceneId: string;
        configId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/generation-configs/{configId}';
};

export type UpdateSceneConfigResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        name: string;
        isDefault: boolean;
        systemPrompt: string;
        stylePreset: 'shonen' | 'shojo' | 'seinen' | 'generic';
        colorMode: 'bw' | 'color' | 'spot_color';
        defaultImageCount: number;
        allowMultiPage: boolean;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateSceneConfigResponse = UpdateSceneConfigResponses[keyof UpdateSceneConfigResponses];

export type SetDefaultConfigData = {
    body: {
        isDefault: boolean;
    };
    path: {
        projectId: string;
        sceneId: string;
        configId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/generation-configs/{configId}/set-default';
};

export type SetDefaultConfigResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        name: string;
        isDefault: boolean;
        systemPrompt: string;
        stylePreset: 'shonen' | 'shojo' | 'seinen' | 'generic';
        colorMode: 'bw' | 'color' | 'spot_color';
        defaultImageCount: number;
        allowMultiPage: boolean;
        metadata: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
    };
};

export type SetDefaultConfigResponse = SetDefaultConfigResponses[keyof SetDefaultConfigResponses];

export type GenerateSceneMangaData = {
    body: {
        configId?: string;
        imageCount: number;
        characterImageRefs?: {
            [key: string]: string;
        };
        additionalContext?: string;
    };
    path: {
        projectId: string;
        sceneId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/generate';
};

export type GenerateSceneMangaResponses = {
    /**
     * Response for status 200
     */
    200: {
        success: boolean;
        jobId: string;
        boardId?: string;
        message: string;
    };
};

export type GenerateSceneMangaResponse = GenerateSceneMangaResponses[keyof GenerateSceneMangaResponses];

export type PreviewPromptData = {
    body: {
        configId?: string;
        characterImageRefs?: {
            [key: string]: string;
        };
        panelCount: number;
    };
    path: {
        projectId: string;
        sceneId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/preview-prompt';
};

export type PreviewPromptResponses = {
    /**
     * Response for status 200
     */
    200: {
        prompts: Array<{
            panelIndex: number;
            title: string;
            prompt: string;
            caption: string;
        }>;
        systemPrompt: string;
        styleDescription: string;
    };
};

export type PreviewPromptResponse = PreviewPromptResponses[keyof PreviewPromptResponses];

export type ListSceneMangaPagesData = {
    body?: never;
    path: {
        projectId: string;
        sceneId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/manga-pages';
};

export type ListSceneMangaPagesResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        sceneId: string;
        tomeId: string;
        chapterId: string;
        jobId: string;
        boardId: string;
        panelId: string;
        pageNumber: number;
        label: string;
        status: 'draft' | 'selected' | 'rejected';
        imageUrl: string | unknown;
        caption: string | unknown;
        prompt: string | unknown;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type ListSceneMangaPagesResponse = ListSceneMangaPagesResponses[keyof ListSceneMangaPagesResponses];

export type DeleteSceneMangaPageData = {
    body?: never;
    path: {
        projectId: string;
        sceneId: string;
        pageId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/manga-pages/{pageId}';
};

export type UpdateSceneMangaPageData = {
    body: {
        label?: string;
        status?: 'draft' | 'selected' | 'rejected';
        imageUrl?: string;
        caption?: string;
        prompt?: string;
    };
    path: {
        projectId: string;
        sceneId: string;
        pageId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/story/scenes/{sceneId}/manga-pages/{pageId}';
};

export type UpdateSceneMangaPageResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        sceneId: string;
        tomeId: string;
        chapterId: string;
        jobId: string;
        boardId: string;
        panelId: string;
        pageNumber: number;
        label: string;
        status: 'draft' | 'selected' | 'rejected';
        imageUrl: string | unknown;
        caption: string | unknown;
        prompt: string | unknown;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateSceneMangaPageResponse = UpdateSceneMangaPageResponses[keyof UpdateSceneMangaPageResponses];

export type ListVersionsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/versions/';
};

export type CreateVersionData = {
    body: {
        branchName: string;
        label: string;
        summary: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/versions/';
};

export type CreateVersionResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        branchName: string;
        versionIndex: number;
        label: string;
        summary: string;
        createdAt: string;
    };
};

export type CreateVersionResponse = CreateVersionResponses[keyof CreateVersionResponses];

export type ListBranchesData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/versions/branches';
};

export type GetVersionData = {
    body?: never;
    path: {
        projectId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/versions/{versionId}';
};

export type GetVersionResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        branchName: string;
        versionIndex: number;
        label: string;
        summary: string;
        createdAt: string;
    };
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type CompareVersionsData = {
    body: {
        leftVersionId: string;
        rightVersionId: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/versions/compare';
};

export type CompareVersionsResponses = {
    /**
     * Response for status 200
     */
    200: {
        left: {
            id: string;
            projectId: string;
            branchName: string;
            versionIndex: number;
            label: string;
            summary: string;
            createdAt: string;
        };
        right: {
            id: string;
            projectId: string;
            branchName: string;
            versionIndex: number;
            label: string;
            summary: string;
            createdAt: string;
        };
        projectChanges: Array<string>;
        countsDelta: {
            [key: string]: number;
        };
    };
};

export type CompareVersionsResponse = CompareVersionsResponses[keyof CompareVersionsResponses];

export type RestoreVersionData = {
    body: {
        label?: string;
        summary?: string;
    };
    path: {
        projectId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/versions/{versionId}/restore';
};

export type RestoreVersionResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        branchName: string;
        versionIndex: number;
        label: string;
        summary: string;
        createdAt: string;
    };
};

export type RestoreVersionResponse = RestoreVersionResponses[keyof RestoreVersionResponses];

export type ListWarningsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        status?: 'open' | 'ignored' | 'resolved';
        kind?: string;
        severity?: 'info' | 'warning' | 'critical';
    };
    url: '/api/projects/{projectId}/warnings/';
};

export type ListWarningsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        fingerprint: string;
        kind: string;
        severity: 'info' | 'warning' | 'critical';
        status: 'open' | 'ignored' | 'resolved';
        title: string;
        message: string;
        entityKind: string;
        entityId: string;
        metadataJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | unknown;
    }>;
};

export type ListWarningsResponse = ListWarningsResponses[keyof ListWarningsResponses];

export type ScanWarningsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/warnings/scan';
};

export type ScanWarningsResponses = {
    /**
     * Response for status 200
     */
    200: {
        items: Array<{
            id: string;
            projectId: string;
            fingerprint: string;
            kind: string;
            severity: 'info' | 'warning' | 'critical';
            status: 'open' | 'ignored' | 'resolved';
            title: string;
            message: string;
            entityKind: string;
            entityId: string;
            metadataJson: {
                [key: string]: unknown;
            };
            createdAt: string;
            updatedAt: string;
            resolvedAt: string | unknown;
        }>;
    };
};

export type ScanWarningsResponse = ScanWarningsResponses[keyof ScanWarningsResponses];

export type UpdateWarningData = {
    body: {
        status: 'open' | 'ignored' | 'resolved';
        note?: string;
    };
    path: {
        projectId: string;
        warningId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/warnings/{warningId}';
};

export type UpdateWarningResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        fingerprint: string;
        kind: string;
        severity: 'info' | 'warning' | 'critical';
        status: 'open' | 'ignored' | 'resolved';
        title: string;
        message: string;
        entityKind: string;
        entityId: string;
        metadataJson: {
            [key: string]: unknown;
        };
        createdAt: string;
        updatedAt: string;
        resolvedAt: string | unknown;
    };
};

export type UpdateWarningResponse = UpdateWarningResponses[keyof UpdateWarningResponses];

export type ListExportsData = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        kind?: 'work' | 'publication';
        status?: 'pending' | 'ready' | 'failed';
        format?: 'json' | 'tree' | 'zip';
    };
    url: '/api/projects/{projectId}/exports/';
};

export type ListExportsResponses = {
    /**
     * Response for status 200
     */
    200: Array<{
        id: string;
        projectId: string;
        kind: 'work' | 'publication';
        format: 'json' | 'tree' | 'zip';
        status: 'pending' | 'ready' | 'failed';
        label: string;
        summary: string;
        artifactPath: string | unknown;
        artifactName: string | unknown;
        metadataJson: {
            [key: string]: unknown;
        };
        sizeBytes: number | unknown;
        createdAt: string;
        updatedAt: string;
        completedAt: string | unknown;
        failedAt: string | unknown;
        errorMessage: string | unknown;
    }>;
};

export type ListExportsResponse = ListExportsResponses[keyof ListExportsResponses];

export type CreateExportData = {
    body: {
        kind: 'work' | 'publication';
        format: 'json' | 'tree' | 'zip';
        label?: string;
        summary: string;
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/exports/';
};

export type CreateExportResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        kind: 'work' | 'publication';
        format: 'json' | 'tree' | 'zip';
        status: 'pending' | 'ready' | 'failed';
        label: string;
        summary: string;
        artifactPath: string | unknown;
        artifactName: string | unknown;
        metadataJson: {
            [key: string]: unknown;
        };
        sizeBytes: number | unknown;
        createdAt: string;
        updatedAt: string;
        completedAt: string | unknown;
        failedAt: string | unknown;
        errorMessage: string | unknown;
    };
};

export type CreateExportResponse = CreateExportResponses[keyof CreateExportResponses];

export type GetExportData = {
    body?: never;
    path: {
        projectId: string;
        exportId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/exports/{exportId}';
};

export type GetExportResponses = {
    /**
     * Response for status 200
     */
    200: {
        id: string;
        projectId: string;
        kind: 'work' | 'publication';
        format: 'json' | 'tree' | 'zip';
        status: 'pending' | 'ready' | 'failed';
        label: string;
        summary: string;
        artifactPath: string | unknown;
        artifactName: string | unknown;
        metadataJson: {
            [key: string]: unknown;
        };
        sizeBytes: number | unknown;
        createdAt: string;
        updatedAt: string;
        completedAt: string | unknown;
        failedAt: string | unknown;
        errorMessage: string | unknown;
    };
};

export type GetExportResponse = GetExportResponses[keyof GetExportResponses];

export type DownloadExportData = {
    body?: never;
    path: {
        projectId: string;
        exportId: string;
    };
    query?: never;
    url: '/api/projects/{projectId}/exports/{exportId}/download';
};

export type GetApiInngestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inngest/';
};

export type PostApiInngestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inngest/';
};

export type PutApiInngestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inngest/';
};
