// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AssetImport
 */
export const zAssetImport = z.object({
    source_path: z.string().min(1),
    name: z.string().min(1).max(255).nullish(),
    slug: z.string().min(1).max(255).nullish(),
    description: z.string().optional().default(''),
    tags_json: z.array(z.string()).optional(),
    mime_type: z.string().max(255).nullish()
});

/**
 * AssetLinkCreate
 */
export const zAssetLinkCreate = z.object({
    asset_id: z.string(),
    target_kind: z.string().min(1).max(64),
    target_id: z.string().min(1).max(36),
    note: z.string().optional().default('')
});

/**
 * AssetLinkRead
 */
export const zAssetLinkRead = z.object({
    id: z.string(),
    project_id: z.string(),
    asset_id: z.string(),
    target_kind: z.string(),
    target_id: z.string(),
    note: z.string(),
    created_at: z.iso.datetime()
});

/**
 * AssetStatus
 */
export const zAssetStatus = z.enum(['active', 'archived']);

/**
 * AssetDetail
 */
export const zAssetDetail = z.object({
    id: z.string(),
    project_id: z.string(),
    slug: z.string(),
    name: z.string(),
    original_filename: z.string(),
    mime_type: z.string(),
    checksum: z.string(),
    size_bytes: z.int(),
    storage_path: z.string(),
    description: z.string(),
    tags_json: z.array(z.string()),
    status: zAssetStatus,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    archived_at: z.iso.datetime().nullish(),
    links: z.array(zAssetLinkRead).optional()
});

/**
 * AssetRead
 */
export const zAssetRead = z.object({
    id: z.string(),
    project_id: z.string(),
    slug: z.string(),
    name: z.string(),
    original_filename: z.string(),
    mime_type: z.string(),
    checksum: z.string(),
    size_bytes: z.int(),
    storage_path: z.string(),
    description: z.string(),
    tags_json: z.array(z.string()),
    status: zAssetStatus,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    archived_at: z.iso.datetime().nullish()
});

/**
 * AssetListResponse
 */
export const zAssetListResponse = z.object({
    items: z.array(zAssetRead)
});

/**
 * AssetUpdate
 */
export const zAssetUpdate = z.object({
    name: z.string().min(1).max(255).nullish(),
    slug: z.string().min(1).max(255).nullish(),
    description: z.string().nullish(),
    tags_json: z.array(z.string()).nullish(),
    status: zAssetStatus.nullish()
});

/**
 * CharacterDuplicate
 */
export const zCharacterDuplicate = z.object({
    name: z.string().min(1).max(255).nullish()
});

/**
 * CharacterImageRead
 */
export const zCharacterImageRead = z.object({
    id: z.string(),
    project_id: z.string(),
    character_id: z.string(),
    file_path: z.string(),
    file_name: z.string(),
    file_size: z.int().nullable(),
    mime_type: z.string(),
    prompt: z.string(),
    strategy: z.string().nullable(),
    style: z.string().nullable(),
    variation_index: z.int().nullable(),
    created_at: z.iso.datetime()
});

/**
 * CharacterImageListResponse
 */
export const zCharacterImageListResponse = z.object({
    items: z.array(zCharacterImageRead)
});

/**
 * CharacterRelationCreate
 */
export const zCharacterRelationCreate = z.object({
    source_character_id: z.string(),
    target_character_id: z.string(),
    relation_type: z.string().min(1).max(64),
    strength: z.int().gte(0).lte(100).optional().default(50),
    narrative_dependency: z.string().optional().default(''),
    notes: z.string().optional().default('')
});

/**
 * CharacterRelationRead
 */
export const zCharacterRelationRead = z.object({
    id: z.string(),
    project_id: z.string(),
    source_character_id: z.string(),
    target_character_id: z.string(),
    relation_type: z.string(),
    strength: z.int(),
    narrative_dependency: z.string(),
    notes: z.string(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * CharacterRelationUpdate
 */
export const zCharacterRelationUpdate = z.object({
    relation_type: z.string().min(1).max(64).nullish(),
    strength: z.int().gte(0).lte(100).nullish(),
    narrative_dependency: z.string().nullish(),
    notes: z.string().nullish()
});

/**
 * CharacterStatus
 */
export const zCharacterStatus = z.enum([
    'active',
    'draft',
    'archived'
]);

/**
 * CharacterCreate
 */
export const zCharacterCreate = z.object({
    name: z.string().min(1).max(255),
    alias: z.string().max(255).nullish(),
    narrative_role: z.string().max(255).nullish(),
    description: z.string().optional().default(''),
    physical_description: z.string().optional().default(''),
    color_palette_json: z.array(z.string()).optional(),
    costume_elements_json: z.array(z.string()).optional(),
    key_traits_json: z.array(z.string()).optional(),
    personality: z.string().optional().default(''),
    narrative_arc: z.string().optional().default(''),
    tags_json: z.array(z.string()).optional(),
    status: zCharacterStatus.optional().default('active')
});

/**
 * CharacterRead
 */
export const zCharacterRead = z.object({
    id: z.string(),
    project_id: z.string(),
    slug: z.string(),
    name: z.string(),
    alias: z.string().nullable(),
    narrative_role: z.string().nullable(),
    description: z.string(),
    physical_description: z.string(),
    color_palette_json: z.array(z.string()),
    costume_elements_json: z.array(z.string()),
    key_traits_json: z.array(z.string()),
    personality: z.string(),
    narrative_arc: z.string(),
    tags_json: z.array(z.string()),
    status: zCharacterStatus,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    archived_at: z.iso.datetime().nullish()
});

/**
 * CharacterListResponse
 */
export const zCharacterListResponse = z.object({
    items: z.array(zCharacterRead)
});

/**
 * CharacterUpdate
 */
export const zCharacterUpdate = z.object({
    name: z.string().min(1).max(255).nullish(),
    alias: z.string().max(255).nullish(),
    narrative_role: z.string().max(255).nullish(),
    description: z.string().nullish(),
    physical_description: z.string().nullish(),
    color_palette_json: z.array(z.string()).nullish(),
    costume_elements_json: z.array(z.string()).nullish(),
    key_traits_json: z.array(z.string()).nullish(),
    personality: z.string().nullish(),
    narrative_arc: z.string().nullish(),
    tags_json: z.array(z.string()).nullish(),
    status: zCharacterStatus.nullish()
});

/**
 * ColorMode
 *
 * Color modes for manga generation.
 */
export const zColorMode = z.enum([
    'bw',
    'color',
    'spot_color'
]);

/**
 * ExportFormat
 */
export const zExportFormat = z.enum([
    'json',
    'tree',
    'zip'
]);

/**
 * ExportKind
 */
export const zExportKind = z.enum(['work', 'publication']);

/**
 * ExportCreate
 */
export const zExportCreate = z.object({
    kind: zExportKind.optional().default('work'),
    format: zExportFormat.optional().default('json'),
    label: z.string().max(255).nullish(),
    summary: z.string().max(2000).optional().default('')
});

/**
 * ExportStatus
 */
export const zExportStatus = z.enum([
    'pending',
    'ready',
    'failed'
]);

/**
 * ExportRead
 */
export const zExportRead = z.object({
    id: z.string(),
    project_id: z.string(),
    kind: zExportKind,
    format: zExportFormat,
    status: zExportStatus,
    label: z.string(),
    summary: z.string(),
    artifact_path: z.string().nullish(),
    artifact_name: z.string().nullish(),
    metadata_json: z.record(z.string(), z.unknown()),
    size_bytes: z.int().nullish(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    completed_at: z.iso.datetime().nullish(),
    failed_at: z.iso.datetime().nullish(),
    error_message: z.string().nullish()
});

/**
 * GenerationBoardPanelRead
 */
export const zGenerationBoardPanelRead = z.object({
    id: z.string(),
    board_id: z.string(),
    step_id: z.string().nullable(),
    order_index: z.int(),
    title: z.string(),
    caption: z.string(),
    prompt: z.string(),
    status: z.string(),
    image_path: z.string(),
    image_name: z.string(),
    metadata_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * GenerationBoardValidateRequest
 */
export const zGenerationBoardValidateRequest = z.object({
    note: z.string().max(4000).nullish()
});

/**
 * GenerationJobStepRead
 */
export const zGenerationJobStepRead = z.object({
    id: z.string(),
    job_id: z.string(),
    order_index: z.int(),
    title: z.string(),
    status: z.string(),
    prompt: z.string(),
    output_text: z.string(),
    artifact_path: z.string().nullable(),
    artifact_name: z.string().nullable(),
    metadata_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    completed_at: z.iso.datetime().nullable(),
    failed_at: z.iso.datetime().nullable(),
    error_message: z.string().nullable()
});

/**
 * GenerationPanelUpdate
 */
export const zGenerationPanelUpdate = z.object({
    status: z.string().nullish(),
    caption: z.string().max(4000).nullish(),
    title: z.string().max(255).nullish()
});

/**
 * GenerationSourceKind
 */
export const zGenerationSourceKind = z.enum([
    'scene',
    'chapter',
    'tome',
    'panel',
    'custom'
]);

/**
 * GenerationBoardRead
 */
export const zGenerationBoardRead = z.object({
    id: z.string(),
    project_id: z.string(),
    job_id: z.string(),
    source_kind: zGenerationSourceKind,
    strategy: z.string(),
    title: z.string(),
    summary: z.string(),
    status: z.string(),
    artifact_path: z.string().nullable(),
    artifact_name: z.string().nullable(),
    metadata_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    validated_at: z.iso.datetime().nullable(),
    panels: z.array(zGenerationBoardPanelRead).optional()
});

/**
 * GenerationJobCreate
 */
export const zGenerationJobCreate = z.object({
    source_kind: zGenerationSourceKind,
    source_id: z.string(),
    source_version_id: z.string().nullish(),
    strategy: z.string().optional().default('direct'),
    model_key: z.string().nullish(),
    mode: z.string().optional().default('separate'),
    selection_ids: z.array(z.string()).optional(),
    grid_rows: z.int().nullish(),
    grid_cols: z.int().nullish(),
    image_count: z.int().nullish(),
    title: z.string().nullish(),
    summary: z.string().optional().default('')
});

/**
 * GenerationJobRead
 */
export const zGenerationJobRead = z.object({
    id: z.string(),
    project_id: z.string(),
    source_kind: zGenerationSourceKind,
    source_id: z.string(),
    source_label: z.string(),
    source_version_id: z.string().nullable(),
    strategy: z.string(),
    model_key: z.string().nullish(),
    model_name: z.string().nullish(),
    model_kind: z.string().nullish(),
    entrypoint: z.string(),
    title: z.string(),
    prompt: z.string(),
    summary: z.string(),
    status: z.string(),
    progress: z.int(),
    metadata_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    completed_at: z.iso.datetime().nullable(),
    failed_at: z.iso.datetime().nullable(),
    error_message: z.string().nullable(),
    steps: z.array(zGenerationJobStepRead).optional(),
    board: zGenerationBoardRead.nullish()
});

/**
 * ModelProviderRead
 */
export const zModelProviderRead = z.object({
    key: z.string(),
    kind: z.string(),
    display_name: z.string(),
    base_url: z.string().nullish(),
    enabled: z.boolean(),
    configured: z.boolean(),
    has_api_key: z.boolean()
});

/**
 * ProjectClone
 */
export const zProjectClone = z.object({
    name: z.string().min(1).max(255).nullish()
});

/**
 * ProjectStatus
 */
export const zProjectStatus = z.enum([
    'draft',
    'active',
    'archived',
    'maintenance'
]);

/**
 * ProjectCreate
 */
export const zProjectCreate = z.object({
    name: z.string().min(1).max(255),
    settings_json: z.record(z.string(), z.unknown()).optional(),
    status: zProjectStatus.optional().default('draft')
});

/**
 * ProjectRead
 */
export const zProjectRead = z.object({
    id: z.string(),
    name: z.string(),
    slug: z.string(),
    status: zProjectStatus,
    root_path: z.string(),
    settings_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    last_opened_at: z.iso.datetime().nullish(),
    archived_at: z.iso.datetime().nullish()
});

/**
 * ProjectListResponse
 */
export const zProjectListResponse = z.object({
    items: z.array(zProjectRead)
});

/**
 * ProjectUpdate
 */
export const zProjectUpdate = z.object({
    name: z.string().min(1).max(255).nullish(),
    status: zProjectStatus.nullish(),
    settings_json: z.record(z.string(), z.unknown()).nullish()
});

/**
 * PromptPreviewRequest
 *
 * Request to preview the generated prompt without running generation.
 */
export const zPromptPreviewRequest = z.object({
    config_id: z.string().nullish(),
    character_image_refs: z.record(z.string(), z.string()).optional(),
    additional_context: z.string().optional().default('')
});

/**
 * PromptPreviewResponse
 *
 * Preview of the prompt that would be sent.
 */
export const zPromptPreviewResponse = z.object({
    system_prompt: z.string(),
    scene_section: z.string(),
    full_prompt: z.string(),
    character_summaries: z.array(z.record(z.string(), z.string())),
    warnings: z.array(z.string()).optional()
});

/**
 * ReferenceSuggestionResponse
 */
export const zReferenceSuggestionResponse = z.object({
    slug: z.string(),
    label: z.string()
});

/**
 * SceneGenerateRequest
 *
 * Request to generate manga pages from a scene.
 */
export const zSceneGenerateRequest = z.object({
    config_id: z.string().nullish(),
    image_count: z.int().gte(1).lte(5).optional().default(1),
    style_override: z.record(z.string(), z.unknown()).nullish(),
    character_image_refs: z.record(z.string(), z.string()).optional(),
    additional_context: z.string().optional().default('')
});

/**
 * SceneGenerateResponse
 *
 * Response after triggering generation.
 */
export const zSceneGenerateResponse = z.object({
    job_id: z.string(),
    status: z.string(),
    message: z.string().optional().default('Generation job started')
});

/**
 * SceneGenerationConfigRead
 *
 * Config read model.
 */
export const zSceneGenerationConfigRead = z.object({
    id: z.string(),
    project_id: z.string(),
    name: z.string(),
    is_default: z.boolean(),
    system_prompt: z.string(),
    style_preset: z.string(),
    color_mode: z.string(),
    default_image_count: z.int(),
    allow_multi_page: z.boolean(),
    metadata_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * SceneMangaPageRead
 *
 * Read model for a scene manga page.
 */
export const zSceneMangaPageRead = z.object({
    id: z.string(),
    project_id: z.string(),
    scene_id: z.string(),
    tome_id: z.string(),
    chapter_id: z.string(),
    job_id: z.string(),
    board_id: z.string(),
    panel_id: z.string(),
    page_number: z.int(),
    label: z.string(),
    status: z.string(),
    image_url: z.string().nullish(),
    caption: z.string().nullish(),
    prompt: z.string().nullish(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * SceneGenerationListResponse
 *
 * List of generation jobs for a scene.
 */
export const zSceneGenerationListResponse = z.object({
    scene_id: z.string(),
    pages: z.array(zSceneMangaPageRead),
    total_pages: z.int()
});

/**
 * SceneMangaPageUpdate
 *
 * Update page metadata.
 */
export const zSceneMangaPageUpdate = z.object({
    label: z.string().max(255).nullish(),
    status: z.enum([
        'draft',
        'selected',
        'rejected'
    ]).nullish()
});

/**
 * StoryReferenceRead
 */
export const zStoryReferenceRead = z.object({
    id: z.string(),
    project_id: z.string(),
    scene_id: z.string(),
    reference_kind: z.string(),
    target_slug: z.string(),
    raw_token: z.string(),
    created_at: z.iso.datetime()
});

/**
 * StoryOrphanReferenceRead
 */
export const zStoryOrphanReferenceRead = z.object({
    reference: zStoryReferenceRead,
    reason: z.string()
});

/**
 * StoryStatus
 */
export const zStoryStatus = z.enum([
    'active',
    'draft',
    'archived'
]);

/**
 * ChapterCreate
 */
export const zChapterCreate = z.object({
    tome_id: z.string(),
    title: z.string().min(1).max(255),
    slug: z.string().min(1).max(255).nullish(),
    synopsis: z.string().optional().default(''),
    status: zStoryStatus.optional().default('active'),
    order_index: z.int().optional().default(0)
});

/**
 * ChapterRead
 */
export const zChapterRead = z.object({
    id: z.string(),
    project_id: z.string(),
    tome_id: z.string(),
    title: z.string(),
    slug: z.string(),
    synopsis: z.string(),
    status: zStoryStatus,
    order_index: z.int(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * ChapterUpdate
 */
export const zChapterUpdate = z.object({
    tome_id: z.string().nullish(),
    title: z.string().min(1).max(255).nullish(),
    slug: z.string().min(1).max(255).nullish(),
    synopsis: z.string().nullish(),
    status: zStoryStatus.nullish(),
    order_index: z.int().nullish()
});

/**
 * SceneCreate
 */
export const zSceneCreate = z.object({
    tome_id: z.string(),
    chapter_id: z.string(),
    title: z.string().min(1).max(255),
    slug: z.string().min(1).max(255).nullish(),
    summary: z.string().optional().default(''),
    content: z.string().optional().default(''),
    notes: z.string().optional().default(''),
    characters_json: z.array(z.string()).optional(),
    tags_json: z.array(z.string()).optional(),
    status: zStoryStatus.optional().default('active'),
    order_index: z.int().optional().default(0)
});

/**
 * SceneRead
 */
export const zSceneRead = z.object({
    id: z.string(),
    project_id: z.string(),
    tome_id: z.string(),
    chapter_id: z.string(),
    title: z.string(),
    slug: z.string(),
    summary: z.string(),
    content: z.string(),
    notes: z.string(),
    characters_json: z.array(z.string()),
    tags_json: z.array(z.string()),
    status: zStoryStatus,
    order_index: z.int(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * SceneUpdate
 */
export const zSceneUpdate = z.object({
    tome_id: z.string().nullish(),
    chapter_id: z.string().nullish(),
    title: z.string().min(1).max(255).nullish(),
    slug: z.string().min(1).max(255).nullish(),
    summary: z.string().nullish(),
    content: z.string().nullish(),
    notes: z.string().nullish(),
    characters_json: z.array(z.string()).nullish(),
    tags_json: z.array(z.string()).nullish(),
    status: zStoryStatus.nullish(),
    order_index: z.int().nullish()
});

/**
 * StorySuggestionRead
 */
export const zStorySuggestionRead = z.object({
    kind: z.string(),
    slug: z.string(),
    title: z.string(),
    label: z.string()
});

/**
 * StylePreset
 *
 * Manga style presets.
 */
export const zStylePreset = z.enum([
    'shonen',
    'shojo',
    'seinen',
    'generic'
]);

/**
 * SceneGenerationConfigCreate
 *
 * Create a new generation config.
 */
export const zSceneGenerationConfigCreate = z.object({
    name: z.string().min(1).max(255),
    is_default: z.boolean().optional().default(false),
    system_prompt: z.string().min(10),
    style_preset: zStylePreset.optional().default('generic'),
    color_mode: zColorMode.optional().default('bw'),
    default_image_count: z.int().gte(1).lte(10).optional().default(1),
    allow_multi_page: z.boolean().optional().default(true),
    metadata_json: z.record(z.string(), z.unknown()).optional()
});

/**
 * SceneGenerationConfigUpdate
 *
 * Update an existing config.
 */
export const zSceneGenerationConfigUpdate = z.object({
    name: z.string().min(1).max(255).nullish(),
    is_default: z.boolean().nullish(),
    system_prompt: z.string().min(10).nullish(),
    style_preset: zStylePreset.nullish(),
    color_mode: zColorMode.nullish(),
    default_image_count: z.int().gte(1).lte(10).nullish(),
    allow_multi_page: z.boolean().nullish(),
    metadata_json: z.record(z.string(), z.unknown()).nullish()
});

/**
 * TomeCreate
 */
export const zTomeCreate = z.object({
    title: z.string().min(1).max(255),
    slug: z.string().min(1).max(255).nullish(),
    synopsis: z.string().optional().default(''),
    status: zStoryStatus.optional().default('active'),
    order_index: z.int().optional().default(0)
});

/**
 * TomeRead
 */
export const zTomeRead = z.object({
    id: z.string(),
    project_id: z.string(),
    title: z.string(),
    slug: z.string(),
    synopsis: z.string(),
    status: zStoryStatus,
    order_index: z.int(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime()
});

/**
 * StorySummaryResponse
 */
export const zStorySummaryResponse = z.object({
    tomes: z.array(zTomeRead),
    chapters: z.array(zChapterRead),
    scenes: z.array(zSceneRead),
    orphan_references: z.array(zStoryOrphanReferenceRead).optional()
});

/**
 * TomeUpdate
 */
export const zTomeUpdate = z.object({
    title: z.string().min(1).max(255).nullish(),
    slug: z.string().min(1).max(255).nullish(),
    synopsis: z.string().nullish(),
    status: zStoryStatus.nullish(),
    order_index: z.int().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VersionBranchRead
 */
export const zVersionBranchRead = z.object({
    branch_name: z.string(),
    version_count: z.int(),
    latest_version_id: z.string().nullish(),
    latest_created_at: z.iso.datetime().nullish()
});

/**
 * VersionCompareRequest
 */
export const zVersionCompareRequest = z.object({
    left_version_id: z.string(),
    right_version_id: z.string()
});

/**
 * VersionCreate
 */
export const zVersionCreate = z.object({
    branch_name: z.string().max(255).optional().default('main'),
    label: z.string().max(255).optional().default('Checkpoint'),
    summary: z.string().optional().default('')
});

/**
 * VersionRead
 */
export const zVersionRead = z.object({
    id: z.string(),
    project_id: z.string(),
    branch_name: z.string(),
    version_index: z.int(),
    label: z.string(),
    summary: z.string(),
    created_at: z.iso.datetime()
});

/**
 * VersionCompareRead
 */
export const zVersionCompareRead = z.object({
    left: zVersionRead,
    right: zVersionRead,
    project_changes: z.array(z.string()).optional(),
    counts_delta: z.record(z.string(), z.int()).optional()
});

/**
 * VersionRestoreRequest
 */
export const zVersionRestoreRequest = z.object({
    label: z.string().max(255).nullish(),
    summary: z.string().nullish()
});

/**
 * VoiceSampleCreate
 */
export const zVoiceSampleCreate = z.object({
    label: z.string().min(1).max(255),
    asset_path: z.string().nullish(),
    voice_notes: z.string().optional().default('')
});

/**
 * VoiceSampleRead
 */
export const zVoiceSampleRead = z.object({
    id: z.string(),
    project_id: z.string(),
    character_id: z.string(),
    asset_path: z.string().nullable(),
    label: z.string(),
    voice_notes: z.string(),
    created_at: z.iso.datetime()
});

/**
 * CharacterDetail
 */
export const zCharacterDetail = z.object({
    id: z.string(),
    project_id: z.string(),
    slug: z.string(),
    name: z.string(),
    alias: z.string().nullable(),
    narrative_role: z.string().nullable(),
    description: z.string(),
    physical_description: z.string(),
    color_palette_json: z.array(z.string()),
    costume_elements_json: z.array(z.string()),
    key_traits_json: z.array(z.string()),
    personality: z.string(),
    narrative_arc: z.string(),
    tags_json: z.array(z.string()),
    status: zCharacterStatus,
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    archived_at: z.iso.datetime().nullish(),
    relationships_summary: z.string().nullish(),
    relations: z.array(zCharacterRelationRead).optional(),
    voice_samples: z.array(zVoiceSampleRead).optional()
});

/**
 * WarningKind
 */
export const zWarningKind = z.enum([
    'missing_character_reference',
    'timeline_incoherence',
    'orphan_reference',
    'orphan_character_image'
]);

/**
 * WarningSeverity
 */
export const zWarningSeverity = z.enum([
    'info',
    'warning',
    'critical'
]);

/**
 * WarningStatus
 */
export const zWarningStatus = z.enum([
    'open',
    'ignored',
    'resolved'
]);

/**
 * WarningRead
 */
export const zWarningRead = z.object({
    id: z.string(),
    project_id: z.string(),
    fingerprint: z.string(),
    kind: zWarningKind,
    severity: zWarningSeverity,
    status: zWarningStatus,
    title: z.string(),
    message: z.string(),
    entity_kind: z.string(),
    entity_id: z.string(),
    metadata_json: z.record(z.string(), z.unknown()),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    resolved_at: z.iso.datetime().nullish()
});

/**
 * WarningScanResponse
 */
export const zWarningScanResponse = z.object({
    items: z.array(zWarningRead)
});

/**
 * WarningUpdate
 */
export const zWarningUpdate = z.object({
    status: zWarningStatus,
    note: z.string().max(500).nullish()
});

/**
 * Successful Response
 */
export const zReadProjectsApiProjectsGetResponse = zProjectListResponse;

export const zCreateProjectRouteApiProjectsPostBody = zProjectCreate;

/**
 * Successful Response
 */
export const zCreateProjectRouteApiProjectsPostResponse = zProjectRead;

export const zReadProjectApiProjectsProjectIdGetPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zReadProjectApiProjectsProjectIdGetResponse = zProjectRead;

export const zPatchProjectApiProjectsProjectIdPatchBody = zProjectUpdate;

export const zPatchProjectApiProjectsProjectIdPatchPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zPatchProjectApiProjectsProjectIdPatchResponse = zProjectRead;

export const zArchiveProjectRouteApiProjectsProjectIdArchivePostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zArchiveProjectRouteApiProjectsProjectIdArchivePostResponse = zProjectRead;

export const zCloneProjectRouteApiProjectsProjectIdClonePostBody = zProjectClone;

export const zCloneProjectRouteApiProjectsProjectIdClonePostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCloneProjectRouteApiProjectsProjectIdClonePostResponse = zProjectRead;

export const zOpenProjectRouteApiProjectsProjectIdOpenPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zOpenProjectRouteApiProjectsProjectIdOpenPostResponse = zProjectRead;

export const zExportProjectRouteApiProjectsProjectIdExportGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Export Project Route Api Projects  Project Id  Export Get
 *
 * Successful Response
 */
export const zExportProjectRouteApiProjectsProjectIdExportGetResponse = z.record(z.string(), z.unknown());

export const zReadAssetsApiProjectsProjectIdAssetsGetPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zReadAssetsApiProjectsProjectIdAssetsGetResponse = zAssetListResponse;

export const zImportAssetRouteApiProjectsProjectIdAssetsImportPostBody = zAssetImport;

export const zImportAssetRouteApiProjectsProjectIdAssetsImportPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zImportAssetRouteApiProjectsProjectIdAssetsImportPostResponse = zAssetRead;

export const zDeleteAssetRouteApiProjectsProjectIdAssetsAssetIdDeletePath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteAssetRouteApiProjectsProjectIdAssetsAssetIdDeleteResponse = z.void();

export const zReadAssetApiProjectsProjectIdAssetsAssetIdGetPath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

/**
 * Successful Response
 */
export const zReadAssetApiProjectsProjectIdAssetsAssetIdGetResponse = zAssetDetail;

export const zUpdateAssetRouteApiProjectsProjectIdAssetsAssetIdPatchBody = zAssetUpdate;

export const zUpdateAssetRouteApiProjectsProjectIdAssetsAssetIdPatchPath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateAssetRouteApiProjectsProjectIdAssetsAssetIdPatchResponse = zAssetRead;

export const zArchiveAssetRouteApiProjectsProjectIdAssetsAssetIdArchivePostPath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

/**
 * Successful Response
 */
export const zArchiveAssetRouteApiProjectsProjectIdAssetsAssetIdArchivePostResponse = zAssetRead;

export const zReadAssetFileApiProjectsProjectIdAssetsAssetIdFileGetPath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

export const zReadAssetLinksApiProjectsProjectIdAssetsAssetIdLinksGetPath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

/**
 * Response Read Asset Links Api Projects  Project Id  Assets  Asset Id  Links Get
 *
 * Successful Response
 */
export const zReadAssetLinksApiProjectsProjectIdAssetsAssetIdLinksGetResponse = z.array(zAssetLinkRead);

export const zCreateAssetLinkRouteApiProjectsProjectIdAssetsAssetIdLinksPostBody = zAssetLinkCreate;

export const zCreateAssetLinkRouteApiProjectsProjectIdAssetsAssetIdLinksPostPath = z.object({
    project_id: z.string(),
    asset_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateAssetLinkRouteApiProjectsProjectIdAssetsAssetIdLinksPostResponse = zAssetLinkRead;

export const zDeleteAssetLinkRouteApiProjectsProjectIdAssetsAssetIdLinksLinkIdDeletePath = z.object({
    project_id: z.string(),
    asset_id: z.string(),
    link_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteAssetLinkRouteApiProjectsProjectIdAssetsAssetIdLinksLinkIdDeleteResponse = z.void();

export const zReadCharactersApiProjectsProjectIdCharactersGetPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zReadCharactersApiProjectsProjectIdCharactersGetResponse = zCharacterListResponse;

export const zCreateCharacterRouteApiProjectsProjectIdCharactersPostBody = zCharacterCreate;

export const zCreateCharacterRouteApiProjectsProjectIdCharactersPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateCharacterRouteApiProjectsProjectIdCharactersPostResponse = zCharacterRead;

export const zReadProjectCharacterImagesApiProjectsProjectIdCharactersImagesGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Read Project Character Images Api Projects  Project Id  Characters Images Get
 *
 * Successful Response
 */
export const zReadProjectCharacterImagesApiProjectsProjectIdCharactersImagesGetResponse = z.record(z.string(), z.array(zCharacterImageRead));

export const zDeleteCharacterRouteApiProjectsProjectIdCharactersCharacterIdDeletePath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteCharacterRouteApiProjectsProjectIdCharactersCharacterIdDeleteResponse = z.void();

export const zReadCharacterApiProjectsProjectIdCharactersCharacterIdGetPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zReadCharacterApiProjectsProjectIdCharactersCharacterIdGetResponse = zCharacterDetail;

export const zUpdateCharacterRouteApiProjectsProjectIdCharactersCharacterIdPatchBody = zCharacterUpdate;

export const zUpdateCharacterRouteApiProjectsProjectIdCharactersCharacterIdPatchPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateCharacterRouteApiProjectsProjectIdCharactersCharacterIdPatchResponse = zCharacterRead;

export const zDuplicateCharacterRouteApiProjectsProjectIdCharactersCharacterIdDuplicatePostBody = zCharacterDuplicate;

export const zDuplicateCharacterRouteApiProjectsProjectIdCharactersCharacterIdDuplicatePostPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zDuplicateCharacterRouteApiProjectsProjectIdCharactersCharacterIdDuplicatePostResponse = zCharacterRead;

export const zArchiveCharacterRouteApiProjectsProjectIdCharactersCharacterIdArchivePostPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zArchiveCharacterRouteApiProjectsProjectIdCharactersCharacterIdArchivePostResponse = zCharacterRead;

export const zCreateRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsPostBody = zCharacterRelationCreate;

export const zCreateRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsPostPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsPostResponse = zCharacterRelationRead;

export const zDeleteRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsRelationIdDeletePath = z.object({
    project_id: z.string(),
    character_id: z.string(),
    relation_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsRelationIdDeleteResponse = z.void();

export const zUpdateRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsRelationIdPatchBody = zCharacterRelationUpdate;

export const zUpdateRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsRelationIdPatchPath = z.object({
    project_id: z.string(),
    character_id: z.string(),
    relation_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateRelationRouteApiProjectsProjectIdCharactersCharacterIdRelationsRelationIdPatchResponse = zCharacterRelationRead;

export const zCreateVoiceSampleRouteApiProjectsProjectIdCharactersCharacterIdVoiceSamplesPostBody = zVoiceSampleCreate;

export const zCreateVoiceSampleRouteApiProjectsProjectIdCharactersCharacterIdVoiceSamplesPostPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateVoiceSampleRouteApiProjectsProjectIdCharactersCharacterIdVoiceSamplesPostResponse = zVoiceSampleRead;

export const zGenerateCharacterImageRouteApiProjectsProjectIdCharactersCharacterIdGenerateImagePostPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

export const zGenerateCharacterImageRouteApiProjectsProjectIdCharactersCharacterIdGenerateImagePostQuery = z.object({
    strategy: z.string().optional().default('portrait'),
    style: z.string().optional().default('realistic'),
    image_count: z.int().optional().default(1),
    model_key: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGenerateCharacterImageRouteApiProjectsProjectIdCharactersCharacterIdGenerateImagePostResponse = zGenerationJobRead;

export const zListCharacterImagesApiProjectsProjectIdCharactersCharacterIdImagesGetPath = z.object({
    project_id: z.string(),
    character_id: z.string()
});

/**
 * Successful Response
 */
export const zListCharacterImagesApiProjectsProjectIdCharactersCharacterIdImagesGetResponse = zCharacterImageListResponse;

export const zDeleteCharacterImageRouteApiProjectsProjectIdCharactersCharacterIdImagesImageIdDeletePath = z.object({
    project_id: z.string(),
    character_id: z.string(),
    image_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteCharacterImageRouteApiProjectsProjectIdCharactersCharacterIdImagesImageIdDeleteResponse = z.void();

export const zReadCharacterImageFileApiProjectsProjectIdCharactersCharacterIdImagesImageIdFileGetPath = z.object({
    project_id: z.string(),
    character_id: z.string(),
    image_id: z.string()
});

export const zReadExportsApiProjectsProjectIdExportsGetPath = z.object({
    project_id: z.string()
});

export const zReadExportsApiProjectsProjectIdExportsGetQuery = z.object({
    kind: zExportKind.nullish(),
    status: zExportStatus.nullish(),
    format: zExportFormat.nullish()
});

/**
 * Response Read Exports Api Projects  Project Id  Exports Get
 *
 * Successful Response
 */
export const zReadExportsApiProjectsProjectIdExportsGetResponse = z.array(zExportRead);

export const zCreateExportRouteApiProjectsProjectIdExportsPostBody = zExportCreate;

export const zCreateExportRouteApiProjectsProjectIdExportsPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateExportRouteApiProjectsProjectIdExportsPostResponse = zExportRead;

export const zReadExportApiProjectsProjectIdExportsExportIdGetPath = z.object({
    project_id: z.string(),
    export_id: z.string()
});

/**
 * Successful Response
 */
export const zReadExportApiProjectsProjectIdExportsExportIdGetResponse = zExportRead;

export const zDownloadExportApiProjectsProjectIdExportsExportIdDownloadGetPath = z.object({
    project_id: z.string(),
    export_id: z.string()
});

export const zReadGenerationJobsApiProjectsProjectIdGenerationJobsGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Read Generation Jobs Api Projects  Project Id  Generation Jobs Get
 *
 * Successful Response
 */
export const zReadGenerationJobsApiProjectsProjectIdGenerationJobsGetResponse = z.array(zGenerationJobRead);

export const zCreateGenerationJobRouteApiProjectsProjectIdGenerationJobsPostBody = zGenerationJobCreate;

export const zCreateGenerationJobRouteApiProjectsProjectIdGenerationJobsPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateGenerationJobRouteApiProjectsProjectIdGenerationJobsPostResponse = zGenerationJobRead;

export const zReadGenerationJobApiProjectsProjectIdGenerationJobsJobIdGetPath = z.object({
    project_id: z.string(),
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zReadGenerationJobApiProjectsProjectIdGenerationJobsJobIdGetResponse = zGenerationJobRead;

export const zReadGenerationBoardsApiProjectsProjectIdGenerationBoardsGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Read Generation Boards Api Projects  Project Id  Generation Boards Get
 *
 * Successful Response
 */
export const zReadGenerationBoardsApiProjectsProjectIdGenerationBoardsGetResponse = z.array(zGenerationBoardRead);

export const zReadGenerationBoardApiProjectsProjectIdGenerationBoardsBoardIdGetPath = z.object({
    project_id: z.string(),
    board_id: z.string()
});

/**
 * Successful Response
 */
export const zReadGenerationBoardApiProjectsProjectIdGenerationBoardsBoardIdGetResponse = zGenerationBoardRead;

/**
 * Payload
 */
export const zValidateGenerationBoardRouteApiProjectsProjectIdGenerationBoardsBoardIdValidatePostBody = zGenerationBoardValidateRequest.nullable();

export const zValidateGenerationBoardRouteApiProjectsProjectIdGenerationBoardsBoardIdValidatePostPath = z.object({
    project_id: z.string(),
    board_id: z.string()
});

/**
 * Successful Response
 */
export const zValidateGenerationBoardRouteApiProjectsProjectIdGenerationBoardsBoardIdValidatePostResponse = zGenerationBoardRead;

export const zUpdateGenerationPanelRouteApiProjectsProjectIdGenerationBoardsBoardIdPanelsPanelIdPatchBody = zGenerationPanelUpdate;

export const zUpdateGenerationPanelRouteApiProjectsProjectIdGenerationBoardsBoardIdPanelsPanelIdPatchPath = z.object({
    project_id: z.string(),
    board_id: z.string(),
    panel_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateGenerationPanelRouteApiProjectsProjectIdGenerationBoardsBoardIdPanelsPanelIdPatchResponse = zGenerationBoardPanelRead;

export const zDownloadGenerationBoardApiProjectsProjectIdGenerationBoardsBoardIdDownloadGetPath = z.object({
    project_id: z.string(),
    board_id: z.string()
});

export const zReadGenerationPanelImageApiProjectsProjectIdGenerationBoardsBoardIdPanelsPanelIdImageGetPath = z.object({
    project_id: z.string(),
    board_id: z.string(),
    panel_id: z.string()
});

export const zListGenerationConfigsApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsGetPath = z.object({
    project_id: z.string()
});

/**
 * Response List Generation Configs Api Projects  Project Id  Story Scenes  Scene Id  Generation Configs Get
 *
 * Successful Response
 */
export const zListGenerationConfigsApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsGetResponse = z.array(zSceneGenerationConfigRead);

export const zCreateGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsPostBody = zSceneGenerationConfigCreate;

export const zCreateGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsPostResponse = zSceneGenerationConfigRead;

export const zDeleteGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdDeletePath = z.object({
    project_id: z.string(),
    config_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdDeleteResponse = z.void();

export const zGetGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdGetPath = z.object({
    project_id: z.string(),
    config_id: z.string()
});

/**
 * Successful Response
 */
export const zGetGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdGetResponse = zSceneGenerationConfigRead;

export const zUpdateGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdPatchBody = zSceneGenerationConfigUpdate;

export const zUpdateGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdPatchPath = z.object({
    project_id: z.string(),
    config_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateGenerationConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdPatchResponse = zSceneGenerationConfigRead;

export const zSetDefaultConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdSetDefaultPostPath = z.object({
    project_id: z.string(),
    config_id: z.string()
});

/**
 * Successful Response
 */
export const zSetDefaultConfigApiProjectsProjectIdStoryScenesSceneIdGenerationConfigsConfigIdSetDefaultPostResponse = zSceneGenerationConfigRead;

export const zGenerateSceneMangaApiProjectsProjectIdStoryScenesSceneIdGeneratePostBody = zSceneGenerateRequest;

export const zGenerateSceneMangaApiProjectsProjectIdStoryScenesSceneIdGeneratePostPath = z.object({
    project_id: z.string(),
    scene_id: z.string()
});

/**
 * Successful Response
 */
export const zGenerateSceneMangaApiProjectsProjectIdStoryScenesSceneIdGeneratePostResponse = zSceneGenerateResponse;

export const zPreviewGenerationPromptApiProjectsProjectIdStoryScenesSceneIdPreviewPromptPostBody = zPromptPreviewRequest;

export const zPreviewGenerationPromptApiProjectsProjectIdStoryScenesSceneIdPreviewPromptPostPath = z.object({
    project_id: z.string(),
    scene_id: z.string()
});

/**
 * Successful Response
 */
export const zPreviewGenerationPromptApiProjectsProjectIdStoryScenesSceneIdPreviewPromptPostResponse = zPromptPreviewResponse;

export const zListSceneMangaPagesApiProjectsProjectIdStoryScenesSceneIdMangaPagesGetPath = z.object({
    project_id: z.string(),
    scene_id: z.string()
});

/**
 * Successful Response
 */
export const zListSceneMangaPagesApiProjectsProjectIdStoryScenesSceneIdMangaPagesGetResponse = zSceneGenerationListResponse;

export const zDeleteSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdDeletePath = z.object({
    project_id: z.string(),
    scene_id: z.string(),
    page_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdDeleteResponse = z.void();

export const zGetSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdGetPath = z.object({
    project_id: z.string(),
    scene_id: z.string(),
    page_id: z.string()
});

/**
 * Successful Response
 */
export const zGetSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdGetResponse = zSceneMangaPageRead;

export const zUpdateSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdPatchBody = zSceneMangaPageUpdate;

export const zUpdateSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdPatchPath = z.object({
    project_id: z.string(),
    scene_id: z.string(),
    page_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateSceneMangaPageApiProjectsProjectIdStoryScenesSceneIdMangaPagesPageIdPatchResponse = zSceneMangaPageRead;

export const zReadStoryApiProjectsProjectIdStoryGetPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zReadStoryApiProjectsProjectIdStoryGetResponse = zStorySummaryResponse;

export const zReadStorySuggestionsApiProjectsProjectIdStorySuggestionsGetPath = z.object({
    project_id: z.string()
});

export const zReadStorySuggestionsApiProjectsProjectIdStorySuggestionsGetQuery = z.object({
    query: z.string().nullish()
});

/**
 * Response Read Story Suggestions Api Projects  Project Id  Story Suggestions Get
 *
 * Successful Response
 */
export const zReadStorySuggestionsApiProjectsProjectIdStorySuggestionsGetResponse = z.array(zStorySuggestionRead);

export const zReadStoryReferencesApiProjectsProjectIdStoryReferencesGetPath = z.object({
    project_id: z.string()
});

export const zReadStoryReferencesApiProjectsProjectIdStoryReferencesGetQuery = z.object({
    scene_id: z.string().nullish()
});

/**
 * Response Read Story References Api Projects  Project Id  Story References Get
 *
 * Successful Response
 */
export const zReadStoryReferencesApiProjectsProjectIdStoryReferencesGetResponse = z.array(zStoryReferenceRead);

export const zReadTomesApiProjectsProjectIdStoryTomesGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Read Tomes Api Projects  Project Id  Story Tomes Get
 *
 * Successful Response
 */
export const zReadTomesApiProjectsProjectIdStoryTomesGetResponse = z.array(zTomeRead);

export const zCreateTomeRouteApiProjectsProjectIdStoryTomesPostBody = zTomeCreate;

export const zCreateTomeRouteApiProjectsProjectIdStoryTomesPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateTomeRouteApiProjectsProjectIdStoryTomesPostResponse = zTomeRead;

export const zDeleteTomeRouteApiProjectsProjectIdStoryTomesTomeIdDeletePath = z.object({
    project_id: z.string(),
    tome_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteTomeRouteApiProjectsProjectIdStoryTomesTomeIdDeleteResponse = z.void();

export const zUpdateTomeRouteApiProjectsProjectIdStoryTomesTomeIdPatchBody = zTomeUpdate;

export const zUpdateTomeRouteApiProjectsProjectIdStoryTomesTomeIdPatchPath = z.object({
    project_id: z.string(),
    tome_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateTomeRouteApiProjectsProjectIdStoryTomesTomeIdPatchResponse = zTomeRead;

export const zReadChaptersApiProjectsProjectIdStoryChaptersGetPath = z.object({
    project_id: z.string()
});

export const zReadChaptersApiProjectsProjectIdStoryChaptersGetQuery = z.object({
    tome_id: z.string().nullish()
});

/**
 * Response Read Chapters Api Projects  Project Id  Story Chapters Get
 *
 * Successful Response
 */
export const zReadChaptersApiProjectsProjectIdStoryChaptersGetResponse = z.array(zChapterRead);

export const zCreateChapterRouteApiProjectsProjectIdStoryChaptersPostBody = zChapterCreate;

export const zCreateChapterRouteApiProjectsProjectIdStoryChaptersPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateChapterRouteApiProjectsProjectIdStoryChaptersPostResponse = zChapterRead;

export const zDeleteChapterRouteApiProjectsProjectIdStoryChaptersChapterIdDeletePath = z.object({
    project_id: z.string(),
    chapter_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteChapterRouteApiProjectsProjectIdStoryChaptersChapterIdDeleteResponse = z.void();

export const zUpdateChapterRouteApiProjectsProjectIdStoryChaptersChapterIdPatchBody = zChapterUpdate;

export const zUpdateChapterRouteApiProjectsProjectIdStoryChaptersChapterIdPatchPath = z.object({
    project_id: z.string(),
    chapter_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateChapterRouteApiProjectsProjectIdStoryChaptersChapterIdPatchResponse = zChapterRead;

export const zReadScenesApiProjectsProjectIdStoryScenesGetPath = z.object({
    project_id: z.string()
});

export const zReadScenesApiProjectsProjectIdStoryScenesGetQuery = z.object({
    chapter_id: z.string().nullish()
});

/**
 * Response Read Scenes Api Projects  Project Id  Story Scenes Get
 *
 * Successful Response
 */
export const zReadScenesApiProjectsProjectIdStoryScenesGetResponse = z.array(zSceneRead);

export const zCreateSceneRouteApiProjectsProjectIdStoryScenesPostBody = zSceneCreate;

export const zCreateSceneRouteApiProjectsProjectIdStoryScenesPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateSceneRouteApiProjectsProjectIdStoryScenesPostResponse = zSceneRead;

export const zDeleteSceneRouteApiProjectsProjectIdStoryScenesSceneIdDeletePath = z.object({
    project_id: z.string(),
    scene_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteSceneRouteApiProjectsProjectIdStoryScenesSceneIdDeleteResponse = z.void();

export const zUpdateSceneRouteApiProjectsProjectIdStoryScenesSceneIdPatchBody = zSceneUpdate;

export const zUpdateSceneRouteApiProjectsProjectIdStoryScenesSceneIdPatchPath = z.object({
    project_id: z.string(),
    scene_id: z.string()
});

/**
 * Successful Response
 */
export const zUpdateSceneRouteApiProjectsProjectIdStoryScenesSceneIdPatchResponse = zSceneRead;

export const zReadReferenceSuggestionsApiProjectsProjectIdReferencesTypeGetPath = z.object({
    project_id: z.string(),
    type: z.string()
});

export const zReadReferenceSuggestionsApiProjectsProjectIdReferencesTypeGetQuery = z.object({
    q: z.string().optional().default('')
});

/**
 * Response Read Reference Suggestions Api Projects  Project Id  References  Type  Get
 *
 * Successful Response
 */
export const zReadReferenceSuggestionsApiProjectsProjectIdReferencesTypeGetResponse = z.array(zReferenceSuggestionResponse);

export const zReadVersionsApiProjectsProjectIdVersionsGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Read Versions Api Projects  Project Id  Versions Get
 *
 * Successful Response
 */
export const zReadVersionsApiProjectsProjectIdVersionsGetResponse = z.array(zVersionRead);

export const zCreateVersionRouteApiProjectsProjectIdVersionsPostBody = zVersionCreate;

export const zCreateVersionRouteApiProjectsProjectIdVersionsPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCreateVersionRouteApiProjectsProjectIdVersionsPostResponse = zVersionRead;

export const zReadVersionBranchesApiProjectsProjectIdVersionsBranchesGetPath = z.object({
    project_id: z.string()
});

/**
 * Response Read Version Branches Api Projects  Project Id  Versions Branches Get
 *
 * Successful Response
 */
export const zReadVersionBranchesApiProjectsProjectIdVersionsBranchesGetResponse = z.array(zVersionBranchRead);

export const zReadVersionApiProjectsProjectIdVersionsVersionIdGetPath = z.object({
    project_id: z.string(),
    version_id: z.string()
});

/**
 * Successful Response
 */
export const zReadVersionApiProjectsProjectIdVersionsVersionIdGetResponse = zVersionRead;

export const zCompareVersionsRouteApiProjectsProjectIdVersionsComparePostBody = zVersionCompareRequest;

export const zCompareVersionsRouteApiProjectsProjectIdVersionsComparePostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zCompareVersionsRouteApiProjectsProjectIdVersionsComparePostResponse = zVersionCompareRead;

/**
 * Payload
 */
export const zRestoreVersionRouteApiProjectsProjectIdVersionsVersionIdRestorePostBody = zVersionRestoreRequest.nullable();

export const zRestoreVersionRouteApiProjectsProjectIdVersionsVersionIdRestorePostPath = z.object({
    project_id: z.string(),
    version_id: z.string()
});

/**
 * Successful Response
 */
export const zRestoreVersionRouteApiProjectsProjectIdVersionsVersionIdRestorePostResponse = zVersionRead;

export const zReadWarningsApiProjectsProjectIdWarningsGetPath = z.object({
    project_id: z.string()
});

export const zReadWarningsApiProjectsProjectIdWarningsGetQuery = z.object({
    status: zWarningStatus.nullish(),
    kind: zWarningKind.nullish(),
    severity: zWarningSeverity.nullish()
});

/**
 * Response Read Warnings Api Projects  Project Id  Warnings Get
 *
 * Successful Response
 */
export const zReadWarningsApiProjectsProjectIdWarningsGetResponse = z.array(zWarningRead);

export const zScanWarningsApiProjectsProjectIdWarningsScanPostPath = z.object({
    project_id: z.string()
});

/**
 * Successful Response
 */
export const zScanWarningsApiProjectsProjectIdWarningsScanPostResponse = zWarningScanResponse;

export const zPatchWarningApiProjectsProjectIdWarningsWarningIdPatchBody = zWarningUpdate;

export const zPatchWarningApiProjectsProjectIdWarningsWarningIdPatchPath = z.object({
    project_id: z.string(),
    warning_id: z.string()
});

/**
 * Successful Response
 */
export const zPatchWarningApiProjectsProjectIdWarningsWarningIdPatchResponse = zWarningRead;

/**
 * Response Health Api Health Get
 *
 * Successful Response
 */
export const zHealthApiHealthGetResponse = z.record(z.string(), z.unknown());

/**
 * Response Config Api Config Get
 *
 * Successful Response
 */
export const zConfigApiConfigGetResponse = z.record(z.string(), z.unknown());

/**
 * Response Models Api Models Get
 *
 * Successful Response
 */
export const zModelsApiModelsGetResponse = z.array(zModelProviderRead);
